### ISSUE TITLE
TML error during "World Validation" causes Terraria to NOT save the world

### ISSUE THREAD

**Issue by PinkDev1** [tModLoader/tModLoader#1066]
### Description

When saving a world (press Save and Exit on in-game menu), TML throws an exception and fails to save the world.

### Log file

Relevant seccion of the log file:

```
[18:46:42] [27/INFO] [StatusText]: Saving map data
[18:46:43] [27/INFO] [StatusText]: Saving world data
[18:46:44] [27/INFO] [StatusText]: Validating world save
//This error is later referenced as **longer error**
[18:46:44] [27/WARN] [tML]: Silently Caught Exception: 
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt64()
   at Terraria.IO.WorldFile.validateWorld(BinaryReader fileIO) in tModLoader\Terraria.IO\WorldFile.cs:line 2081
   at Terraria.IO.WorldFile.saveWorld(Boolean useCloudSaving, Boolean resetTime) in tModLoader\Terraria.IO\WorldFile.cs:line 329
   at Terraria.WorldGen.SaveAndQuitCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 1897
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

//This second error is later referenced to as **shorter error**
[18:46:44] [27/ERROR] [Terraria]: World Validation
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt64()
   at Terraria.IO.WorldFile.validateWorld(BinaryReader fileIO) in tModLoader\Terraria.IO\WorldFile.cs:line 2082
[18:46:44] [27/INFO] [TerrariaOverhaul]: [OverhaulWorld] Saved season TerrariaOverhaul.Common.Systems.Gameplay.Seasons.Summer
```

### Steps to reproduce

1. Create a world with the mods listed below
2. Create a character with the mods listed below
3. Load the world with the mods listed below
4. Make any change on the world (break a couple of blocks, kill a boss, anything)
5. Save the world via _Save and Exit_

### Expected behavior 

TML should save the changes made to the world.

### Actual behavior

The changes made to the world, are NOT saved.

### Reproduction frequency

On my tests, this error ocurs 70% of the time (It ocurred 7/10 times)

### Additional Information

Terraria 1.3.5.3
tModLoader v0.11.7.5 Windows client | Running on NetFramework 4.8

List of mods (from GREPing the log with "Initializing:"):

- AlchemistNPC v9.3
- AutoReroll v1.6.2.1
- AutoTrash v0.5
- BetterNightSky v1.5.0.1
- BetterTaxes v2.4.0
- BossChecklist v1.1.4.1
- CalamityLootSwap v1.5.1
- CalamityMod v1.4.5.2
- CalamityModMusic v1.4.5.2
- CalValEX v5.4.4.1
- Census v0.3.1
- CheatSheet v0.6.6
- ClamExtraMusic v1.0.7.5
- DespawnAbleTownNpcs v1.0
- DisableCorruptionSpread v1.1
- ExtensibleInventory v1.5.2.1
- Fargowiltas v2.2.1
- FasterDamages v1.5
- FasterPickaxes v1.5
- FKBossHealthBar v1.3.2
- FullHealthRespawn v0.0.1
- HamstarHelpers v5.9.1.2
- imkSushisMod v4.3.1
- IndustrialPickaxes v4.6.1
- LowHealthBeep v1.0
- Luiafk v1.0.0.130
- MagicStorage v0.4.3.5
- MaxStackExtra v1.1.0.4
- ModLoader v0.11.7.5
- MoreAccessories v2.3
- MorePotions v4.100
- NoMoreTombs v1.0.1
- NoSpeedLimit v1.0.0.3
- OmniSwing v3.0.1
- PreHMTeleportation v0.3.4
- PylonNPC v1.0
- RecipeBrowser v0.8.7
- ReducedGrinding v6.0
- SmartDoors v1.3.3
- TerrariaOverhaul v4.5.0.4
- VeinMiner v1.3.1
- WingSlot v1.7.3
- WMITF v2.6.2

**Note that out of the 7 fails, the _longer error_ only appeared once. However, the _shorter error_ appeared on all 7 fails.
All _shorter errors_ are identical.**

The player data is always saved succesfully, as well as his position on the world.

The error does NOT ocurr with all mods disabled (Main Menu -> Mods -> Disable All).

**Comment by JavidPack** [comment]
I believe the world not saving is caused by the Calamity update.

**Comment by PinkDev1** [comment]
Damn, you're right.
Interestingly enough, the error only seems to happen on old worlds (2 weeks) generated with calamity. On newly generated worlds, the error doesn't happen at all.

Oh, well. Guess I'll have to move to the Calimity issue tracker. Thanks for the quick response!

**Comment by PinkDev1** [comment]
To any future readers:

From [Calamity's bug list](https://docs.google.com/document/d/1SrEO6CS_cwbSZFUYqKkzU-de9AH-e8I6vrlYDVdDsl0) (gotten from [Calamity's Discord server](https://discord.gg/9kXd2PG) ):

[SAVE] After updating to v1.4.5.002, progress made in your world doesn’t save correctly, often reverting any changes made after saving the world.
Solution: Generate a new world in v1.4.5.002. This should only happen in worlds generated in v1.4.5.001, as it is believed to be due to naturally generated Draedon's Charging Stations. Breaking all of these in your world may also fix the issue, but this is not confirmed. Both the Charging Stations and Fuel Factories will be destroyed when updating to v1.4.5.003 to fix this issue.
