### ISSUE TITLE
I have a problem where i cant run calamity bec it says memory ran out

### ISSUE THREAD

**Issue by heyboiso** [tModLoader/tModLoader#1069]
I have a problem where i cant run calamity bec it says memory ran out Here is my specs

RAM:4gb
CPU:Intel core 2 duo e7500 2.9 ghz dual core
GPU:Intel (R) 4 Series Express Chipset Family

Here is the log file
===========================================================
[17:37:56] [1/INFO] [tML]: Starting tModLoader v0.11.7.5 Windows client (9/4/2020)
[17:37:56] [1/INFO] [tML]: Running on NetFramework 4.8
[17:37:56] [1/INFO] [tML]: Executable: E:\Terraria 1.4.0.5\TModLoader\tModLoader.exe
[17:37:56] [1/INFO] [tML]: Working Directory: E:\Terraria 1.4.0.5\TModLoader
[17:37:56] [1/INFO] [tML]: Launch Parameters: 
[17:37:56] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null
[17:37:56] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null
[17:37:56] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[17:37:56] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[17:37:56] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[17:37:57] [1/INFO] [tML]: Checking GOG or manual installation...
[17:37:57] [1/INFO] [tML]: GOG or manual installation OK.
[17:37:57] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[17:38:00] [1/DEBUG] [Terraria]: Graphics Device: Intel(R) Q45/Q43 Express Chipset {Width:1024 Height:768 Format:Color AspectRatio:1.333333}
[17:38:00] [1/WARN] [tML]: Silently Caught Exception: 
Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Could not find a Direct3D device that supports the XNA Framework HiDef profile.

Verify that a suitable graphics device is installed.

Make sure the desktop is not locked, and that no other application is running in full screen mode.

Avoid running under Remote Desktop or as a Windows service.

Check the display properties to make sure hardware acceleration is set to Full.
   at Microsoft.Xna.Framework.GraphicsDeviceManager.FindBestPlatformDevice(Boolean anySuitableDevice)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.FindBestDevice(Boolean anySuitableDevice)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ChangeDevice(Boolean forceCreate)
   at Terraria.Main.SetGraphicsProfileInternal() in tModLoader\Terraria\Main.cs:line 2434
   at Terraria.Main.SetGraphicsProfile(GraphicsProfile profile) in tModLoader\Terraria\Main.cs:line 2428
   at Terraria.Main.LoadContent() in tModLoader\Terraria\Main.cs:line 6849
   at Microsoft.Xna.Framework.Game.Initialize()
   at Terraria.Main.ClientInitialize() in tModLoader\Terraria\Main.cs:line 6760
   at Terraria.Main.Initialize() in tModLoader\Terraria\Main.cs:line 6743
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 250
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 228
   at Terraria.WindowsLaunch.Main(String[] args) in tModLoader\Terraria\WindowsLaunch.cs:line 72

[17:38:00] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[17:38:01] [1/INFO] [Terraria]: Loaded 1000 vanilla assets
[17:38:02] [1/INFO] [Terraria]: Loaded 2000 vanilla assets
[17:38:03] [1/INFO] [Terraria]: Loaded 3000 vanilla assets
[17:38:03] [1/INFO] [Terraria]: Loaded 4000 vanilla assets
[17:38:03] [1/INFO] [Terraria]: Loaded 5000 vanilla assets
[17:38:05] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 800 -> 848, Height: 480, Fullscreen: False -> True, Display: \\.\DISPLAY1
[17:38:06] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 848 -> 1024, Height: 480 -> 768, Fullscreen: True, Display: \\.\DISPLAY1
[17:38:12] [6/DEBUG] [tML]: Assembly Resolve:  -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[17:38:12] [6/DEBUG] [tML]: Assembly Resolve:  -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[17:38:13] [7/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[17:38:14] [7/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Pdb, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[17:38:14] [6/INFO] [Terraria]: JIT loading finished
[17:38:14] [7/INFO] [tML]: Unloading mods
[17:38:15] [7/INFO] [tML]: Finding Mods...
[17:38:15] [7/INFO] [tML]: Sandboxing: CalamityMod
[17:38:18] [7/INFO] [tML]: Sandboxing: HEROsMod
[17:38:18] [7/INFO] [tML]: Instantiating Mods...
[17:38:19] [7/INFO] [tML]: Initializing: ModLoader v0.11.7.5
[17:38:19] [7/INFO] [tML]: Initializing: CalamityMod v1.4.4.4
[17:38:26] [28/WARN] [tML]: Silently Caught Exception: 
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.Xna.Framework.Helpers.GetExceptionFromResult(UInt32 result)
   at Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(UInt32 result)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, UInt32 usage, _D3DPOOL pool, SurfaceFormat format)
   at Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height)
   at Terraria.ModLoader.IO.ImageIO.<>c__DisplayClass8_0.<RawToTexture2DAsync>b__0() in tModLoader\Terraria.ModLoader.IO\ImageIO.cs:line 98
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[17:38:26] [28/FATAL] [tML]: Game ran out of memory. You'll have to find which mod is consuming lots of memory, and contact the devs or remove it.
[17:42:30] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 1024, Height: 768, Fullscreen: True, Display: \\.\DISPLAY1
[17:42:32] [1/INFO] [tML]: Loading Cancelled
[17:42:33] [1/INFO] [tML]: Loading Cancelled
===========================================================

Pls Help Me I want to Play Calamity

**Comment by Mirsario** [comment]
See  https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#outofmemoryexception

**Comment by heyboiso** [comment]
That didnt Help

**Comment by Mirsario** [comment]
If you're running calamity alone and crashing with not that many applications open - I'm not sure if anything other than not playing with that mod can help you. Calamity is most likely the most resource-intensive mod, and may just not run at all on devices with 2-4 GBs of RAM. We'll aim towards improvements in tML for 1.4 to ensure that mods become less RAM heavy overall, but until then - shrug.

**Comment by heyboiso** [comment]
Thx For Telling Me But other mods like SOA-Thorium-A awakened only Elements Awoken Work so i can generate worlds when running thorium and A awakened and Elements awoken but the game says memory ran out when i try to enter the world with thorium and ancients awakened only elements awoken run correctly

**Comment by heyboiso** [comment]
i have thorium log i will put it right here

[08:47:43] [1/INFO] [tML]: Starting tModLoader v0.11.7.5 Windows client (9/9/2020)
[08:47:43] [1/INFO] [tML]: Running on NetFramework 4.8
[08:47:43] [1/INFO] [tML]: Executable: E:\Terraria 1.4.0.5\TModLoader\tModLoader.exe
[08:47:43] [1/INFO] [tML]: Working Directory: E:\Terraria 1.4.0.5\TModLoader
[08:47:43] [1/INFO] [tML]: Launch Parameters: 
[08:47:43] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null
[08:47:43] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null
[08:47:43] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[08:47:44] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[08:47:44] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[08:47:44] [1/INFO] [tML]: Checking GOG or manual installation...
[08:47:45] [1/INFO] [tML]: GOG or manual installation OK.
[08:47:45] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[08:47:47] [1/DEBUG] [Terraria]: Graphics Device: Intel(R) Q45/Q43 Express Chipset {Width:1024 Height:768 Format:Color AspectRatio:1.333333}
[08:47:47] [1/WARN] [tML]: Silently Caught Exception: 
Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Could not find a Direct3D device that supports the XNA Framework HiDef profile.

Verify that a suitable graphics device is installed.

Make sure the desktop is not locked, and that no other application is running in full screen mode.

Avoid running under Remote Desktop or as a Windows service.

Check the display properties to make sure hardware acceleration is set to Full.
   at Microsoft.Xna.Framework.GraphicsDeviceManager.FindBestPlatformDevice(Boolean anySuitableDevice)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.FindBestDevice(Boolean anySuitableDevice)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ChangeDevice(Boolean forceCreate)
   at Terraria.Main.SetGraphicsProfileInternal() in tModLoader\Terraria\Main.cs:line 2434
   at Terraria.Main.SetGraphicsProfile(GraphicsProfile profile) in tModLoader\Terraria\Main.cs:line 2428
   at Terraria.Main.LoadContent() in tModLoader\Terraria\Main.cs:line 6849
   at Microsoft.Xna.Framework.Game.Initialize()
   at Terraria.Main.ClientInitialize() in tModLoader\Terraria\Main.cs:line 6760
   at Terraria.Main.Initialize() in tModLoader\Terraria\Main.cs:line 6743
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 250
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 228
   at Terraria.WindowsLaunch.Main(String[] args) in tModLoader\Terraria\WindowsLaunch.cs:line 72

[08:47:47] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[08:48:00] [1/INFO] [Terraria]: Loaded 1000 vanilla assets
[08:48:09] [1/INFO] [Terraria]: Loaded 2000 vanilla assets
[08:48:18] [1/INFO] [Terraria]: Loaded 3000 vanilla assets
[08:48:27] [1/INFO] [Terraria]: Loaded 4000 vanilla assets
[08:48:35] [1/INFO] [Terraria]: Loaded 5000 vanilla assets
[08:48:45] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 800 -> 848, Height: 480, Fullscreen: False -> True, Display: \\.\DISPLAY1
[08:48:45] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 848 -> 1024, Height: 480 -> 768, Fullscreen: True, Display: \\.\DISPLAY1
[08:48:51] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 1024, Height: 768, Fullscreen: True, Display: \\.\DISPLAY1
[08:48:52] [6/DEBUG] [tML]: Assembly Resolve:  -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[08:48:52] [6/DEBUG] [tML]: Assembly Resolve:  -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[08:48:53] [6/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[08:48:53] [6/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Pdb, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[08:48:54] [5/INFO] [Terraria]: JIT loading finished
[08:48:54] [7/INFO] [tML]: Unloading mods
[08:48:55] [7/INFO] [tML]: Finding Mods...
[08:48:55] [7/INFO] [tML]: Sandboxing: BossChecklist
[08:48:56] [7/INFO] [tML]: Sandboxing: HEROsMod
[08:48:56] [7/INFO] [tML]: Sandboxing: RecipeBrowser
[08:48:56] [7/INFO] [tML]: Sandboxing: ThoriumMod
[08:48:57] [7/INFO] [tML]: Instantiating Mods...
[08:48:59] [7/INFO] [tML]: Initializing: ModLoader v0.11.7.5
[08:48:59] [7/INFO] [tML]: Initializing: BossChecklist v1.1.4.1
[08:48:59] [7/DEBUG] [tML]: Assembly Resolve: BossChecklist_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[08:48:59] [7/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[08:48:59] [7/WARN] [tML]: Upgraded Reference MonoMod.RuntimeDetour -> Version=19.12.19.1 -> 20.5.14.1
[08:48:59] [7/DEBUG] [tML]: Hook On.Terraria.GameContent.Events.DD2Event::WinInvasionInternal() added by BossChecklist_0
[08:48:59] [7/INFO] [BossChecklist]: Boss Log integration messages will not be logged.
[08:49:00] [7/INFO] [tML]: Initializing: HEROsMod v0.3.5.1
[08:49:00] [7/INFO] [tML]: Initializing: RecipeBrowser v0.8.7
[08:49:00] [7/DEBUG] [tML]: Hook On.Terraria.Recipe::FindRecipes() added by RecipeBrowser_0
[08:49:00] [7/DEBUG] [tML]: Hook On.Terraria.Player::AdjTiles() added by RecipeBrowser_0
[08:49:00] [7/INFO] [tML]: Initializing: ThoriumMod v1.6.3.8
[08:49:04] [7/DEBUG] [tML]: Hook On.Terraria.Player::ApplyDamageToNPC(NPC, int, float, int, bool) added by ThoriumMod_0
[08:49:04] [7/INFO] [tML]: Setting up...
[08:49:05] [7/INFO] [tML]: Loading: ModLoader v0.11.7.5
[08:49:05] [7/INFO] [tML]: Loading: BossChecklist v1.1.4.1
[08:49:05] [7/INFO] [tML]: Loading: HEROsMod v0.3.5.1
[08:49:05] [7/INFO] [tML]: Loading: RecipeBrowser v0.8.7
[08:49:05] [7/INFO] [tML]: Loading: ThoriumMod v1.6.3.8
[08:49:07] [7/INFO] [tML]: Adding Recipes...
[08:49:07] [7/DEBUG] [tML]: Assembly Resolve:  -> RecipeBrowser_0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[08:49:07] [7/DEBUG] [tML]: Assembly Resolve:  -> RecipeBrowser_0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[08:49:21] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 1024, Height: 768, Fullscreen: True -> False, Display: \\.\DISPLAY1
[08:49:25] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 1024 -> 792, Height: 768 -> 757, Fullscreen: False, Display: \\.\DISPLAY1
[08:49:25] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 792 -> 800, Height: 757, Fullscreen: False, Display: \\.\DISPLAY1
[08:49:27] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 800 -> 1024, Height: 757 -> 745, Fullscreen: False, Display: \\.\DISPLAY1
[08:49:27] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 1024, Height: 745, Fullscreen: False, Display: \\.\DISPLAY1
[08:49:27] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 1024, Height: 745, Fullscreen: False, Display: \\.\DISPLAY1
[08:49:28] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 1024 -> 800, Height: 745 -> 757, Fullscreen: False, Display: \\.\DISPLAY1
[08:49:29] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 800, Height: 757, Fullscreen: False, Display: \\.\DISPLAY1
[08:49:42] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach, Width: 800, Height: 757 -> 600, Fullscreen: False, Display: \\.\DISPLAY1
[08:49:49] [34/INFO] [Terraria]: Loading World: M3ST4R WORLD, IsCloud=False
[08:49:49] [34/INFO] [StatusText]: Resetting game objects
[08:49:51] [34/WARN] [tML]: Silently Caught Exception: 
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Terraria.WorldGen.clearWorld() in tModLoader\Terraria\WorldGen.cs:line 2237
   at Terraria.IO.WorldFile.LoadHeader(BinaryReader reader) in tModLoader\Terraria.IO\WorldFile.cs:line 1404
   at Terraria.IO.WorldFile.LoadWorld_Version2(BinaryReader reader) in tModLoader\Terraria.IO\WorldFile.cs:line 1292
   at Terraria.IO.WorldFile.loadWorld(Boolean loadFromCloud) in tModLoader\Terraria.IO\WorldFile.cs:line 187
   at Terraria.WorldGen.do_playWorldCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 1938
   at Terraria.WorldGen.playWorldCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 1920
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[08:49:51] [34/FATAL] [tML]: Game ran out of memory. You'll have to find which mod is consuming lots of memory, and contact the devs or remove it.
