### ISSUE TITLE
Game freezes in a blizzard while playing with mods

### ISSUE THREAD

**Issue by Frozty2** [tModLoader/tModLoader#1195]
### Description

When playing on mods and going to snow biome while there is blizzard character freezes and only way to exit it is alt f4(inventory not working).
### Log file

Exception from logs:
[18:37:23] [1/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Audio.LegacySoundStyle.GetRandomSound()
   at Terraria.Audio.ActiveSound.Play()
   at Terraria.Audio.ActiveSound..ctor(SoundStyle style)
   at Terraria.Main.PlayTrackedSound(SoundStyle style)
   at Terraria.Player.UpdateBiomes()
   at DMD<Terraria.Player::Update>(Player this, Int32 i)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

### Steps to reproduce

1. Create world
2. Make a rain
3. Go to snow biome

### Reproduction frequency

Every time

**Comment by imabigboi** [comment]
i have the same problem too

**Comment by Mirsario** [comment]
This has just been fixed in 0.11.7.8.
