### ISSUE TITLE
Game keeps crashing if i try to open it

### ISSUE THREAD

**Issue by brndnishere** [tModLoader/tModLoader#1198]
Whenever i try to open up the game it instantly crashes here is the error message I'm getting with the clinet.log folder, please help me.
---------------------------
Terraria: Error (tModLoader v0.11.7.8)
---------------------------
System.UnauthorizedAccessException: Access to the path is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.__Error.WinIOError()

   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)

   at Terraria.ModLoader.Logging.GetNewLogFile(String baseName)

   at Terraria.ModLoader.Logging.ConfigureAppenders()

   at Terraria.ModLoader.Logging.Init()

   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

A client.log file containing error information has been generated in
C:\Users\milly\OneDrive\Documents\My Games\Terraria\ModLoader\Logs
(You will need to share this file if asking for help)
---------------------------
OK   
---------------------------
[client.log](https://github.com/tModLoader/tModLoader/files/5532421/client.log)

**Comment by JavidPack** [comment]
This issue is caused by various antivirus settings preventing the game from saving to a specific directory: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#systemunauthorizedaccessexception-access-to-the-path-is-denied
