### ISSUE TITLE
Tmodloader 64bit Splitscreen Mod Issue

### ISSUE THREAD

**Issue by FluffyAzzy** [tModLoader/tModLoader#1258]
### Description
Hosting a server for second application to join for local co-op freezes on "Found server"

### Log file
[01:34:12] [1/INFO] [tML]: Starting tModLoader v0.11.7.8 Win32NT client (12/30/2020)
[01:34:12] [1/INFO] [tML]: Running on NetFramework 4.8
[01:34:12] [1/INFO] [tML]: Engine: FNA
[01:34:12] [1/INFO] [tML]: Executable: C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader64bit.exe
[01:34:12] [1/INFO] [tML]: Working Directory: C:\Program Files (x86)\Steam\steamapps\common\tModLoader
[01:34:12] [1/INFO] [tML]: Launch Parameters: 
[01:34:12] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[01:34:12] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[01:34:12] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[01:34:12] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[01:34:12] [1/DEBUG] [tML]: Assembly Resolve:  -> FNA, Version=20.4.0.0, Culture=neutral, PublicKeyToken=null
[01:34:12] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[01:34:12] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[01:34:12] [1/DEBUG] [tML]: Assembly Resolve: ReLogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> FNA, Version=17.4.0.0, Culture=neutral, PublicKeyToken=null
[01:34:12] [1/WARN] [tML]: Upgraded Reference FNA -> Version=17.4.0.0 -> 20.4.0.0
[01:34:13] [1/WARN] [tML]: Silently Caught Exception: 
System.DllNotFoundException: Unable to load DLL '/usr/lib/libobjc.A.dylib': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Xna.Framework.Graphics.MetalDevice.sel_registerName(Byte[] name)
   at Microsoft.Xna.Framework.Graphics.MetalDevice..cctor()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow()
   at Microsoft.Xna.Framework.Game..ctor()
   at Terraria.Main..ctor()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)

[01:34:13] [1/DEBUG] [tML]: Hook On.Terraria.IO.WorldFile::LoadChests(BinaryReader) added by tModLoader
[01:34:13] [1/DEBUG] [tML]: Hook On.Terraria.IO.WorldFile::SaveChests(BinaryWriter) added by tModLoader
[01:34:13] [1/INFO] [tML]: Checking Steam installation...
[01:34:13] [1/INFO] [tML]: Steam installation OK.
[01:34:14] [1/DEBUG] [Terraria]: Graphics Device: Generic PnP Monitor {{Width:1536 Height:864 Format:Color}}
[01:34:16] [1/INFO] [Terraria]: Loaded 1000 vanilla assets
[01:34:17] [1/INFO] [Terraria]: Loaded 2000 vanilla assets
[01:34:17] [1/INFO] [Terraria]: Loaded 3000 vanilla assets
[01:34:18] [1/INFO] [Terraria]: Loaded 4000 vanilla assets
[01:34:18] [1/INFO] [Terraria]: Loaded 5000 vanilla assets
[01:34:19] [1/DEBUG] [tML]: Assembly Resolve: FNA, Version=20.4.0.0, Culture=neutral, PublicKeyToken=null -> ReLogic
[01:34:19] [1/WARN] [tML]: Upgraded Reference ReLogic -> Version= -> 1.0.0.0
[01:34:19] [1/DEBUG] [tML]: Assembly Resolve: FNA, Version=20.4.0.0, Culture=neutral, PublicKeyToken=null -> ReLogic
[01:34:19] [1/WARN] [tML]: Upgraded Reference ReLogic -> Version= -> 1.0.0.0
[01:34:20] [1/DEBUG] [tML]: Fallback synchronization context assigned
[01:34:20] [10/INFO] [Terraria]: JIT loading finished
[01:34:24] [3/INFO] [tML]: Unloading mods
[01:34:24] [3/INFO] [tML]: Finding Mods...
[01:34:25] [3/INFO] [tML]: Sandboxing: AAMod
[01:34:26] [3/INFO] [tML]: Sandboxing: AmuletOfManyMinions
[01:34:26] [3/INFO] [tML]: Sandboxing: blackmagic
[01:34:26] [3/INFO] [tML]: Sandboxing: CalamityMod
[01:34:27] [3/INFO] [tML]: Sandboxing: CheatSheet
[01:34:27] [3/INFO] [tML]: Sandboxing: DarkMagicMod
[01:34:27] [3/INFO] [tML]: Sandboxing: EsperClass
[01:34:27] [3/INFO] [tML]: Sandboxing: ExpandedSentries
[01:34:27] [3/INFO] [tML]: Sandboxing: ExtrSummonWeapons
[01:34:27] [3/INFO] [tML]: Sandboxing: FinalFantasyTidusWeapons
[01:34:27] [3/INFO] [tML]: Sandboxing: FirstTechMagic
[01:34:27] [3/INFO] [tML]: Sandboxing: FlyingMinionsIgnoreTerrain
[01:34:27] [3/INFO] [tML]: Sandboxing: JoostMod
[01:34:27] [3/INFO] [tML]: Sandboxing: MagicMod
[01:34:27] [3/INFO] [tML]: Sandboxing: MagicWeaponsPlus
[01:34:27] [3/INFO] [tML]: Sandboxing: MinionsTargetDummy
[01:34:27] [3/INFO] [tML]: Sandboxing: Monstroriam
[01:34:27] [3/INFO] [tML]: Sandboxing: MSB
[01:34:27] [3/INFO] [tML]: Sandboxing: ThoriumMod
[01:34:28] [3/INFO] [tML]: Sandboxing: OrchidMod
[01:34:28] [3/INFO] [tML]: Sandboxing: PhazonMinions
[01:34:28] [3/INFO] [tML]: Sandboxing: QwertysRandomContent
[01:34:28] [3/INFO] [tML]: Sandboxing: Redemption
[01:34:29] [3/INFO] [tML]: Sandboxing: SplitScreen
[01:34:29] [3/DEBUG] [tML]: Generating ModuleDefinition for FNA, Version=17.3.0.0, Culture=neutral, PublicKeyToken=null
[01:34:29] [3/INFO] [tML]: Sandboxing: StarterClasses
[01:34:29] [3/INFO] [tML]: Sandboxing: SummonerAdditions
[01:34:29] [3/INFO] [tML]: Sandboxing: SummonerOverhaul
[01:34:29] [3/INFO] [tML]: Sandboxing: SummonerPlus
[01:34:29] [3/INFO] [tML]: Sandboxing: SummonersAssociation
[01:34:29] [3/INFO] [tML]: Sandboxing: SummonersDream
[01:34:29] [3/INFO] [tML]: Sandboxing: SummonPack
[01:34:29] [3/INFO] [tML]: Sandboxing: TerrariaExtra
[01:34:29] [3/INFO] [tML]: Sandboxing: WeaponsOPlenty
[01:34:29] [3/INFO] [tML]: Instantiating Mods...
[01:34:30] [3/DEBUG] [tML]: Assembly Resolve: AAMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null
[01:34:30] [3/DEBUG] [tML]: Assembly Resolve: AAMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> FNA, Version=17.3.0.0, Culture=neutral, PublicKeyToken=null
[01:34:30] [3/WARN] [tML]: Upgraded Reference FNA -> Version=17.3.0.0 -> 20.4.0.0
[01:34:30] [3/DEBUG] [tML]: Assembly Resolve: DarkMagicMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> Terraria, Version=1.3.5.1, Culture=neutral, PublicKeyToken=null
[01:34:35] [3/INFO] [tML]: Initializing: ModLoader v0.11.7.8
[01:34:37] [3/INFO] [tML]: Initializing: AAMod v1.0.3.2
[01:34:37] [3/DEBUG] [tML]: Assembly Resolve:  -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[01:34:37] [3/DEBUG] [tML]: Assembly Resolve:  -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[01:34:40] [3/DEBUG] [tML]: Assembly Resolve: AAMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[01:34:41] [3/INFO] [AAMod]: AAMod AA log
[01:34:41] [3/DEBUG] [tML]: Hook On.Terraria.Wiring::ActuateForced(int, int) added by AAMod_0
[01:34:41] [3/DEBUG] [tML]: Hook On.Terraria.Wiring::Actuate(int, int) added by AAMod_0
[01:34:41] [3/WARN] [tML]: Silently Caught Exception: 
System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Terraria.IO.Preferences.Get[T](String name, T defaultValue)
   at AAMod.Config.ReadConfig() in AAMod\AAConfig.cs:line 66
   at AAMod.Config.Load() in AAMod\AAConfig.cs:line 40
   at AAMod.AAMod.Load() in AAMod.cs:line 277
   at Terraria.ModLoader.ModContent.<>c.<Load>b__38_0(Mod mod)
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction)
   at Terraria.ModLoader.ModContent.Load(CancellationToken token)
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

[01:34:42] [3/INFO] [tML]: Initializing: AmuletOfManyMinions v0.4.0.1
[01:34:42] [3/INFO] [tML]: Initializing: blackmagic v0.8.0
[01:34:42] [3/INFO] [tML]: Initializing: CalamityMod v1.4.5.7
[01:34:51] [3/DEBUG] [tML]: Assembly Resolve: CalamityMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null
[01:34:51] [3/WARN] [tML]: Upgraded Reference MonoMod.Utils -> Version=20.5.14.1 -> 19.12.19.1
[01:34:51] [3/DEBUG] [tML]: Hook IL.Terraria.Wiring::HitWireSingle(int, int) modified by CalamityMod_0
[01:34:51] [3/DEBUG] [tML]: Assembly Resolve: CalamityMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[01:34:51] [3/WARN] [tML]: Upgraded Reference Mono.Cecil -> Version=0.11.2.0 -> 0.11.1.0
[01:34:51] [3/DEBUG] [tML]: Hook On.Terraria.Main::InitLifeBytes() added by CalamityMod_0
[01:34:51] [3/DEBUG] [tML]: Hook On.Terraria.NPC::SlimeRainSpawns(int) added by CalamityMod_0
[01:34:51] [3/DEBUG] [tML]: Hook IL.Terraria.WorldGen::MakeDungeon(int, int) modified by CalamityMod_0
[01:34:51] [3/DEBUG] [tML]: Hook IL.Terraria.WorldGen::GrowLivingTree(int, int) modified by CalamityMod_0
[01:34:51] [3/DEBUG] [tML]: Hook On.Terraria.WorldGen::OpenDoor(int, int, int) added by CalamityMod_0
[01:34:51] [3/DEBUG] [tML]: Hook On.Terraria.WorldGen::CloseDoor(int, int, bool) added by CalamityMod_0
[01:34:51] [3/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime() modified by CalamityMod_0
[01:34:51] [3/DEBUG] [tML]: Hook On.Terraria.Main::UpdateTime_SpawnTownNPCs() added by CalamityMod_0
[01:34:52] [3/INFO] [tML]: Initializing: CheatSheet v0.6.6.2
[01:34:52] [3/INFO] [tML]: Initializing: DarkMagicMod v0.30
[01:34:52] [3/INFO] [tML]: Initializing: EsperClass v0.6.1
[01:34:53] [3/INFO] [tML]: Initializing: ExpandedSentries v0.980
[01:34:53] [3/INFO] [tML]: Initializing: ExtrSummonWeapons v0.16
[01:34:53] [3/INFO] [tML]: Initializing: FinalFantasyTidusWeapons v1.4
[01:34:53] [3/INFO] [tML]: Initializing: FirstTechMagic v1.2
[01:34:54] [3/INFO] [tML]: Initializing: FlyingMinionsIgnoreTerrain v1.0.6
[01:34:54] [3/INFO] [tML]: Initializing: JoostMod v0.8.1.3
[01:34:55] [3/INFO] [tML]: Initializing: MagicMod v0.1.9
[01:34:55] [3/INFO] [tML]: Initializing: MagicWeaponsPlus v3.0.1
[01:34:56] [3/INFO] [tML]: Initializing: MinionsTargetDummy v1.0
[01:34:56] [3/DEBUG] [tML]: Hook On.Terraria.NPC::CanBeChasedBy(object, bool) added by MinionsTargetDummy_0
[01:34:56] [3/INFO] [tML]: Initializing: Monstroriam v2.1.1
[01:34:56] [3/INFO] [tML]: Initializing: MSB v0.2
[01:34:56] [3/INFO] [tML]: Initializing: ThoriumMod v1.6.3.13
[01:35:02] [3/DEBUG] [tML]: Hook On.Terraria.Player::ApplyDamageToNPC(NPC, int, float, int, bool) added by ThoriumMod_0
[01:35:03] [3/INFO] [tML]: Initializing: OrchidMod v1.3.0.3
[01:35:04] [3/INFO] [tML]: Initializing: PhazonMinions v0.1.2.3
[01:35:04] [3/INFO] [tML]: Initializing: QwertysRandomContent v0.22.11
[01:35:13] [3/INFO] [tML]: Initializing: Redemption v0.7.9.62
[01:35:17] [3/DEBUG] [tML]: Hook On.Terraria.Wiring::ActuateForced(int, int) added by Redemption_0
[01:35:17] [3/DEBUG] [tML]: Hook On.Terraria.Wiring::Actuate(int, int) added by Redemption_0
[01:35:18] [3/INFO] [tML]: Initializing: SplitScreen v2.0.1
[01:35:18] [3/DEBUG] [tML]: Assembly Resolve: SplitScreen_0, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null -> SplitScreen_0Harmony_0, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
[01:35:18] [3/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SplitScreen.Main_Update_Patcher.Transpiler(IEnumerable`1 instructions)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Harmony.CodeTranspiler.<>c__DisplayClass10_0.<GetResult>b__0(MethodInfo transpiler)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Harmony.CodeTranspiler.GetResult(ILGenerator generator, MethodBase method)
   at Harmony.ILCopying.MethodBodyReader.FinalizeILCodes(List`1 transpilers, List`1 endLabels, List`1 endBlocks)
   at Harmony.ILCopying.MethodCopier.Finalize(List`1 endLabels, List`1 endBlocks)
   at Harmony.MethodPatcher.CreatePatchedMethod(MethodBase original, String harmonyInstanceID, List`1 prefixes, List`1 postfixes, List`1 transpilers)
   at Harmony.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo, String instanceID)
   at Harmony.PatchProcessor.Patch()
   at Harmony.HarmonyInstance.<PatchAll>b__7_0(Type type)
   at Harmony.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at Harmony.HarmonyInstance.PatchAll(Assembly assembly)
   at SplitScreen.SplitScreenMod.Load()
   at Terraria.ModLoader.ModContent.<>c.<Load>b__38_0(Mod mod)
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction)
   at Terraria.ModLoader.ModContent.Load(CancellationToken token)
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

[01:35:18] [3/WARN] [tML]: Silently Caught Exception: 
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at SplitScreen.Main_Update_Patcher.Transpiler(IEnumerable`1 instructions)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Harmony.CodeTranspiler.<>c__DisplayClass10_0.<GetResult>b__0(MethodInfo transpiler)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Harmony.CodeTranspiler.GetResult(ILGenerator generator, MethodBase method)
   at Harmony.ILCopying.MethodBodyReader.FinalizeILCodes(List`1 transpilers, List`1 endLabels, List`1 endBlocks)
   at Harmony.ILCopying.MethodCopier.Finalize(List`1 endLabels, List`1 endBlocks)
   at Harmony.MethodPatcher.CreatePatchedMethod(MethodBase original, String harmonyInstanceID, List`1 prefixes, List`1 postfixes, List`1 transpilers)
   at Harmony.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo, String instanceID)
   at Harmony.PatchProcessor.Patch()
   at Harmony.HarmonyInstance.<PatchAll>b__7_0(Type type)
   at Harmony.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at Harmony.HarmonyInstance.PatchAll(Assembly assembly)
   at SplitScreen.SplitScreenMod.Load()
   at Terraria.ModLoader.ModContent.<>c.<Load>b__38_0(Mod mod)
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction)
   at Terraria.ModLoader.ModContent.Load(CancellationToken token)
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

[01:35:19] [3/INFO] [tML]: Initializing: StarterClasses v1.4.1.2
[01:35:19] [1/DEBUG] [tML]: Assembly Resolve: SplitScreen_0, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null -> SplitScreen_RawInputSharp_0, Version=1.0.6721.35761, Culture=neutral, PublicKeyToken=null
[01:35:19] [1/WARN] [tML]: Silently Caught Exception: 
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.ToInt32()
   at RawInputSharp.RawInput.GetRawInputDevices()
   at RawInputSharp.RawInput..ctor()
   at RawInputSharp.RawMouseInput..ctor()
   at SplitScreen.Mice.MultipleMiceManager.RegisterMice()
   at SplitScreen.SplitScreenMod.<Load>b__8_1(Object <sender>, EventArgs <e>)
   at SplitScreen.Main_Update_Patcher.Prefix(GameTime gameTime)
   at DoUpdate_Patch1(Object gameTime, GameTime )
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)

[01:35:19] [1/ERROR] [Terraria]: System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.ToInt32()
   at RawInputSharp.RawInput.GetRawInputDevices()
   at RawInputSharp.RawInput..ctor()
   at RawInputSharp.RawMouseInput..ctor()
   at SplitScreen.Mice.MultipleMiceManager.RegisterMice()
   at SplitScreen.SplitScreenMod.<Load>b__8_1(Object <sender>, EventArgs <e>)
   at SplitScreen.Main_Update_Patcher.Prefix(GameTime gameTime)
   at DoUpdate_Patch1(Object gameTime, GameTime )
   at Terraria.Main.Update(GameTime gameTime)
[01:35:19] [3/INFO] [tML]: Initializing: SummonerAdditions v1.2
[01:35:19] [3/INFO] [tML]: Initializing: SummonerOverhaul v1.2.1
[01:35:20] [3/INFO] [tML]: Initializing: SummonerPlus v0.2.3
[01:35:20] [3/INFO] [tML]: Initializing: SummonersAssociation v0.4.5.3
[01:35:20] [3/DEBUG] [tML]: Assembly Resolve: SummonersAssociation_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.RuntimeDetour, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null
[01:35:20] [3/WARN] [tML]: Upgraded Reference MonoMod.RuntimeDetour -> Version=20.5.14.1 -> 19.12.19.1
[01:35:20] [3/DEBUG] [tML]: Hook On.Terraria.Main::DrawInterface_39_MouseOver() added by SummonersAssociation_0
[01:35:20] [3/DEBUG] [tML]: Hook On.Terraria.Player::UpdateMinionTarget() added by SummonersAssociation_0
[01:35:20] [3/DEBUG] [tML]: Hook On.Terraria.ModLoader.ProjectileLoader::ProjectileAI(Projectile) added by SummonersAssociation_0
[01:35:20] [3/INFO] [tML]: Initializing: SummonersDream v0.12
[01:35:20] [3/INFO] [tML]: Initializing: SummonPack v1.0
[01:35:20] [3/INFO] [tML]: Initializing: TerrariaExtra v0.4.0
[01:35:21] [3/INFO] [tML]: Initializing: WeaponsOPlenty v0.3.6
[01:35:21] [3/INFO] [tML]: Setting up...
[01:35:21] [3/INFO] [tML]: Loading: ModLoader v0.11.7.8
[01:35:22] [3/INFO] [tML]: Loading: AAMod v1.0.3.2
[01:35:23] [3/WARN] [tML]: Ancients Awakened: TheStride. You have set ModNPC.banner or ModNPC.bannerItem, but not the other. Make sure you set both, check your spelling, and that the item exists if you are using mod.ItemType(). Report this to the Ancients Awakened developers.
[01:35:23] [3/INFO] [tML]: Loading: AmuletOfManyMinions v0.4.0.1
[01:35:23] [3/INFO] [tML]: Loading: blackmagic v0.8.0
[01:35:24] [3/INFO] [tML]: Loading: CalamityMod v1.4.5.7
[01:35:25] [3/INFO] [CalamityMod]: ModLoader version > 0.11.7.7 detected. Mechworm UUID workaround is disabled.
[01:35:26] [3/INFO] [tML]: Loading: CheatSheet v0.6.6.2
[01:35:26] [3/INFO] [tML]: Loading: DarkMagicMod v0.30
[01:35:26] [3/INFO] [tML]: Loading: EsperClass v0.6.1
[01:35:27] [3/INFO] [tML]: Loading: ExpandedSentries v0.980
[01:35:28] [3/INFO] [tML]: Loading: ExtrSummonWeapons v0.16
[01:35:28] [3/INFO] [tML]: Loading: FinalFantasyTidusWeapons v1.4
[01:35:28] [3/INFO] [tML]: Loading: FirstTechMagic v1.2
[01:35:29] [3/INFO] [tML]: Loading: FlyingMinionsIgnoreTerrain v1.0.6
[01:35:29] [3/INFO] [tML]: Loading: JoostMod v0.8.1.3
[01:35:29] [3/INFO] [tML]: Loading: MagicMod v0.1.9
[01:35:30] [3/INFO] [tML]: Loading: MagicWeaponsPlus v3.0.1
[01:35:30] [3/INFO] [tML]: Loading: MinionsTargetDummy v1.0
[01:35:30] [3/INFO] [tML]: Loading: Monstroriam v2.1.1
[01:35:30] [3/INFO] [tML]: Loading: MSB v0.2
[01:35:31] [3/INFO] [tML]: Loading: ThoriumMod v1.6.3.13
[01:35:33] [3/INFO] [tML]: Loading: OrchidMod v1.3.0.3
[01:35:34] [3/INFO] [tML]: Loading: PhazonMinions v0.1.2.3
[01:35:34] [3/INFO] [tML]: Loading: QwertysRandomContent v0.22.11
[01:35:34] [3/INFO] [tML]: Loading: Redemption v0.7.9.62
[01:35:36] [3/INFO] [tML]: Loading: SplitScreen v2.0.1
[01:35:36] [3/INFO] [tML]: Loading: StarterClasses v1.4.1.2
[01:35:36] [3/INFO] [tML]: Loading: SummonerAdditions v1.2
[01:35:36] [3/INFO] [tML]: Loading: SummonerOverhaul v1.2.1
[01:35:36] [3/INFO] [tML]: Loading: SummonerPlus v0.2.3
[01:35:37] [3/INFO] [tML]: Loading: SummonersAssociation v0.4.5.3
[01:35:37] [3/INFO] [tML]: Loading: SummonersDream v0.12
[01:35:37] [3/INFO] [tML]: Loading: SummonPack v1.0
[01:35:37] [3/INFO] [tML]: Loading: TerrariaExtra v0.4.0
[01:35:37] [3/INFO] [tML]: Loading: WeaponsOPlenty v0.3.6
[01:35:38] [3/INFO] [tML]: RAM usage: 4.5 GB
[01:35:38] [3/INFO] [tML]: Adding Recipes...
[01:35:58] [1/DEBUG] [tML]: Process.Start (UseShellExecute = False): "tModLoaderServer.exe" -autoshutdown -password "Happy" -lang 1 -world "C:\Users\Jackson Russell\Documents\My Games\Terraria\ModLoader\Worlds\New_Beginnings.wld" -modpath "C:\Users\Jackson Russell\Documents\My Games\Terraria\ModLoader\Mods" -steam -localsteamid 76561199095308646 -lobby friends
[01:35:58] [3/INFO] [Terraria]: Connecting to 127.0.0.1:7777
[01:36:00] [3/WARN] [tML]: Silently Caught Exception: 
System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:7777
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at Terraria.Net.Sockets.TcpSocket.Terraria.Net.Sockets.ISocket.Connect(RemoteAddress address)
   at Terraria.Netplay.TcpClientLoop(Object threadContext)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

[01:36:31] [1/WARN] [tML]: Silently Caught Exception: 
System.ArgumentOutOfRangeException: Field isActive was not found in Type Terraria.Main
Parameter name: propName
   at SplitScreen.AccessExtensions.SetPrivateFieldValue[T](Object obj, String propName, T val)
   at SplitScreen.Main_Update_Patcher.Prefix(GameTime gameTime)
   at DoUpdate_Patch1(Object gameTime, GameTime )
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)

[01:36:31] [1/ERROR] [Terraria]: System.ArgumentOutOfRangeException: Field isActive was not found in Type Terraria.Main
Parameter name: propName
   at SplitScreen.AccessExtensions.SetPrivateFieldValue[T](Object obj, String propName, T val)
   at SplitScreen.Main_Update_Patcher.Prefix(GameTime gameTime)
   at DoUpdate_Patch1(Object gameTime, GameTime )
   at Terraria.Main.Update(GameTime gameTime)
[01:36:31] [1/ERROR] [Terraria]: System.ArgumentOutOfRangeException: Field isActive was not found in Type Terraria.Main
Parameter name: propName
(Sorry if this isn't is it; first time posting o here)

### Steps to reproduce
Start up Tmodloader 64bit
Download the splitscreen mod
Click Multiplayer
Host a session
Set up a password (I leave mine blank)
Wait till it says "Server found" and see the game freeze up

### Expected behavior 
Starts up the world like normal and lets the second application join by typing the server name as "localhost" and the IP as "7777." I know this cause it worked on the 32bit version flawlessly.

### Actual behavior
Upon saying "Found server," the game freezes or softlocks, not sure which it is, but the cursor goes invisible on the window when its over the menu screen.
### Reproduction frequency
100% since I started Tmodloader 64bit. 

### Additional Information
This worked perfectly fine on the 32bit version without fail. Haven't tried replicating this back on the 32bit version due to having enough mods that 32bit can't load all of it. Will try disabling multiple mods and run splitscreen if it helps pinpoint the problem. Also, I'm not too familiar with modding, so apologies in advance if something doesn't add up or is incorrect. I'll do my best to give out as much info as possible.

**Comment by FluffyAzzy** [comment]
Is it cut off? I'm not seeing everything I typed and not sure if that's what others see too.

**Comment by FluffyAzzy** [comment]
There we go, fixed it.

**Comment by Mirsario** [comment]
Issues with 64-bit tML go to its discord - https://discord.gg/DY8cx5T
Issues with mods go to their authors. This seems like the latter.
![image](https://user-images.githubusercontent.com/6795251/103340280-b8bde500-4a94-11eb-9dbc-4453e3e877e8.png)

**Comment by FluffyAzzy** [comment]
Thank you
