### ISSUE TITLE
[1.3] Strange Bug Leading to player.map corrupting, Index out of bounds

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1332]
### Description
Warning: this bug comes from ~ october 7 - Nov 10. Not sure if still relevant.
Basically, player.map data corrupts on unloading/reloading. 

### Log file
[Test Set .zip](https://github.com/tModLoader/tModLoader/files/5993415/Test.Set.zip)

Only care about "81b984ce-3296-4fba-acc3-ff401f0b6c58.map".

### Steps to reproduce

1. Place the .map files in provided player, place the .wld files in your folder
2. Open tML with no mods enabled
3. Open the world with the player - you should get a fairly filled in map
4. Save and quit the world
5. Corrupt the map data on your next load in to the world.

### Expected behavior 
Map data is preserved through reloads

### Actual behavior
Its not preserved.

### Reproduction frequency
Within the test set provided, 100%. Hard to reproduce otherwise, fairly rare.

### Additional Information
The mod list (I'm lazy rn, so pics in word doc for now):
[ModList of Map breaking.docx](https://github.com/tModLoader/tModLoader/files/5993435/ModList.of.Map.breaking.docx)

**Comment by direwolf420** [comment]
```
[22:47:15] [8/INFO] [Terraria]: Loading World: aaawtf, IsCloud=False
[22:47:15] [8/INFO] [StatusText]: Resetting game objects
[22:47:15] [8/INFO] [StatusText]: Loading world data
[22:47:15] [8/INFO] [StatusText]: Settling liquids
[22:47:16] [8/INFO] [StatusText]: Loading map data
[22:47:16] [8/WARN] [tML]: Silently Caught Exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.Map.MapHelper.LoadMapVersion2(BinaryReader fileIO, Int32 release) in tModLoader\Terraria.Map\MapHelper.cs:line 1991
   at Terraria.Map.WorldMap.Load() in tModLoader\Terraria.Map\WorldMap.cs:line 92
   at Terraria.WorldGen.do_playWorldCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 1995
   at Terraria.WorldGen.playWorldCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 1920
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Here's a log I have from when I entered a world with a player that previously played on the world, but with vastly different mod lists

**Comment by Solxanich** [comment]
Yup, same error, 
``System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.Map.MapHelper.LoadMapVersion2(BinaryReader fileIO, Int32 release)
   at Terraria.Map.WorldMap.Load()
   at Terraria.WorldGen.do_playWorldCallBack(Object threadContext)
   at Terraria.WorldGen.playWorldCallBack(Object threadContext)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()``

At least confirms the cause gives a consistent error tossed, although an unhelpful one.

**Comment by JavidPack** [comment]
Stale issue, probably fixed, closing.

**Comment by JavidPack** [comment]
Apparently still happens, reopening.

**Comment by DBotThePony** [comment]
Can confirm this still happens, albeit i have different cause (on load):

```
System.IO.EndOfStreamException: Чтение после конца потока невозможно.
   в System.IO.__Error.EndOfFile()
   в System.IO.BinaryReader.ReadByte()
   в Terraria.Map.MapHelper.LoadMapVersion2(BinaryReader fileIO, Int32 release)
   в Terraria.Map.WorldMap.Load()
   в Terraria.Netplay.InnerClientLoop()
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()
```

[8ff43b9a-e71e-42de-b026-a8376d7e35fa.zip](https://github.com/tModLoader/tModLoader/files/8637126/8ff43b9a-e71e-42de-b026-a8376d7e35fa.zip)

100% guaranteed corruption (for all players on multiplayer map) on player save, albeit this bug appeared after **removing** a mod
