### ISSUE TITLE
[1.4] Signinificant performance drop after .NET 5 amd 64 bit port

### ISSUE THREAD

**Issue by DarkLight66** [tModLoader/tModLoader#1470]
### Description
After PR #1086 was merged, tModLoader now uses ~1450 mb of ram on the main menu after starting the game, as opposed to ~875 before .NET 5. After entering a small world, the memory usage increases to ~1750 mb, and the fps stays at ~35 while having frame skip on and trippy lighting, as opposed to 1050 mb and ~55 fps on the same settings.

### Log file
[client_PreNet5.log](https://github.com/tModLoader/tModLoader/files/6361906/client_PreNet5.log)
[client_PostNet5.log](https://github.com/tModLoader/tModLoader/files/6361905/client_PostNet5.log)

### Steps to reproduce
1. Compile tModLoader using `buildDebug.bat`
2. Start game through `start-tModLoader.bat`

### Expected behavior 
Game performance remains roughly the same as before.

### Actual behavior
Game performance drops significantly.

### Reproduction frequency
Always

### Additional Information
My PC has 4gb of ram, yet it has a 64bit processor and OS (Windows 8.1). I don't believe this is a problem with Terraria 1.4.2.2, which was merged right after, as vanilla doesn't have the same memory usage and fps issues, and seems to be similar in performance as tModLoader before .Net 5. 
As i understand it, the .NET 5 / 64 bit port wouldn't have benefited me much, if at all, and if it instead reduces the game's performance in my case, it would only be detrimental for me.

**Comment by zauberparacelsus** [comment]
I notice that you compiled tModLoader as a debug build.  Debug builds of anything typically have increased memory usage and reduced performance due to the debugging symbols and other things that are typically not included in a release build.

**Comment by DarkLight66** [comment]
I know, and both pre and post .NET 5 builds i compared were debug ones. I also tried a release version of the post .NET 5 one and the performance was pretty much the same as the debug build.

**Comment by Mirsario** [comment]
Comparing Debug builds is also not fair, CLR and CoreCLR are like night and day. I'm also running into some stuttering and etc, but this seems to me like debugging/VS issues. since I can't make out anything in performance snapshots.

**Comment by andrewlord607** [comment]
I have a laptop released in 2011, so I also decided to measure the performance.

CPU: i5-2450M, 2.5 Ghz
GPU: AMD Radeon HD 7650M
RAM: 8gb
O/S : Windows 7 64bit
Old HDD

I ran the game for .NET 5 via cmd command `dotnet tModLoader.dll`
Here are my results, all values are approximate.

In debug
|           | before .NET 5 (menu/in game) | after .NET 5 (menu/in game) |
|:---------:|:----------------------------:|:---------------------------:|
| CPU usage |            10%/26%           |           26%/28%           |
| GPU usage |         0-40%/0-100%         |           100%/80%          |
| RAM usage |         970Mb/1200Mb         |         820Mb/1100Mb        |
|    FPS    |          60fps/54fps         |         60fps/55fps         |

In release
|           | before .NET 5 (menu/in game) | after .NET 5 (menu/in game) |
|:---------:|:----------------------------:|:---------------------------:|
| CPU usage |            10%/20%           |           26%/28%           |
| GPU usage |           0%/0-100%          |           100%/80%          |
| RAM usage |         940Mb/1130Mb         |         820Mb/1100Mb        |
|    FPS    |             60fps            |            60fps            |

First, I confirm that the difference between debug and release is negligible.
Second, memory usage remained at about the same level or decreased in favor of .NET5
Third, the use of CPU and GPU has increased, but has become more stable (abrupt jumps have disappeared)

Feels like that the overall performance has only improved, and the most significant visible change is only in the use of the GPU(especially in the menu for .NET5). Perhaps the problem lies in using OpenGL instead of d3d9 (If there is a way to change the type of rendering, then this can be checked)

P.S. I have various old computer hardware at home (even with an approximate processor like DarkLight66's) and could test on it in the beginning of may.

**Comment by DarkLight66** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/6370924/client.log)
Log taken from the release version. As i mentioned above, there's little difference in performance. This particular error which keeps appearing seems worrying: 
```
[19:27:09] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.ArgumentNullException: Value cannot be null. (Parameter 'ptr')
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice.LoadGLEntryPoints(String driver)
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice..ctor(PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateGLDevice(PresentationParameters presentationParameters, GraphicsAdapter adapter)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 204
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 175
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 44
   ```
   Searching the web for the first line of this error shows results suggesting, as i understand it, some kind of mismatch in processor architecture. There's also a mention of a similar error in the tModLoader FNA thread in the Terraria forums ([link](https://forums.terraria.org/index.php?threads/1-3-tmodloader-fna-32bit-64bit-branch-of-tml.75644/page-33#post-1942060)).

**Comment by Mirsario** [comment]
Yup, looks like we'll be switching to either Vulkan or Directx on windows. Need to update FNA first.

**Comment by Mirsario** [comment]
I've updated FNA to the latest version. It should now default to using D3D11 instead of OpenGL. Test the performance again.

**Comment by DarkLight66** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/6373530/client.log) (release version)
After the update to FNA and by using D3D11 (which does look it's the default now, though i tested both without and with `/gldevice:D3D11`), tModLoader now uses less memory overall (1200 in main menu, 1500 on a small world), and although my fps seems to still stay around 30, turning off backgrounds now brings it up to 60, which is similar to what i experienced in vanilla.
Using OpenGL (`/gldevice:OpenGL`) now doesn't throw the `Value cannot be null. (Parameter 'ptr')` error anymore, though still uses as much memory as before, and disabling backgrounds doesn't make much of a difference to fps, though it didn't make a difference before FNA was updated either.
