### ISSUE TITLE
tModLoader repeatedly ran out of memory

### ISSUE THREAD

**Issue by heh372** [tModLoader/tModLoader#1511]
### Description
Whenever I tried to switch outside of tml using win+tab then switch back, the screen becomes white and the program itself stops responding, then there's the error message "Game ran out of memory. You'll have to find which mod is consuming lots of memory, and contact the devs or remove it." This happens randomly when using win+tab, by that I mean sometimes it works fine but sometimes it crashes.
I do have a lot of mods installed/enabled, this includes: calamity (mod+music), thorium, luiafk, alchemistnpc (not lite), cheat sheet and veinminer.
My pc's display is 3840x2160 and I run the game at 1920x1080
I have an extra memory chip installed so the total memory is 32GB, there's no way a 2D pixel game can use up to 32 gb of ram, and the task manager proves it.
However, there's an issue, the window resizes a few times before entering fullscreen. I've learned this from the following log messages:
"[13:22:42] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 800 -> 1280, Height: 480 -> 720, Fullscreen: False -> True, Display: \\.\DISPLAY1
[13:22:43] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1280 -> 1920, Height: 720 -> 1080, Fullscreen: True, Display: \\.\DISPLAY1
[13:22:44] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1080, Fullscreen: True, Display: \\.\DISPLAY1"
These are always in the log file and the effect is noticeable too.

Does this affect it? Because I'm pretty sure it's related.

I'm pretty sure it's the game because this only happens when using win+tab. In some cases, this always happens when using win+tab. That means it never happens in-game, so it's not actually the game running out of the memory, more like a bug which happens when resizing the window.

### Log file

Client is completely normal, until:

[13:36:05] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1080, Fullscreen: True, Display: \\.\DISPLAY1
[13:36:06] [1/WARN] [tML]: Silently Caught Exception: 
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.Xna.Framework.Helpers.GetExceptionFromResult(UInt32 result)
   at Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(UInt32 result)
   at Microsoft.Xna.Framework.Graphics.RenderTargetHelper.CreateSurfaces(GraphicsDevice graphicsDevice)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D.RecreateAndPopulateObject()
   at Microsoft.Xna.Framework.Graphics.DeviceResourceManager.RecreateResources(_D3DPOOL pool, Boolean deviceRecreated)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(PresentationParameters presentationParameters, GraphicsAdapter graphicsAdapter)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ChangeDevice(Boolean forceCreate)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.EnsureDevicePlatform()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.BeginDraw()
   at Microsoft.Xna.Framework.Game.BeginDraw()
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Paint(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameWindow.OnPaint()
   at Microsoft.Xna.Framework.WindowsGameWindow.mainForm_Paint(Object sender, PaintEventArgs e)
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Form.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at Microsoft.Xna.Framework.WindowsGameForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at Microsoft.Xna.Framework.Input.UnsafeNativeMethods.CallWindowProc(IntPtr lpPrevWndFunc, IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Microsoft.Xna.Framework.Input.WindowMessageHooker.Hook.WndProc(IntPtr msgWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at ReLogic.OS.Windows.WindowsApi.CallWindowProc(IntPtr lpPrevWndFunc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at ReLogic.OS.Windows.WindowsMessageHook.WndProc(IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

[13:36:06] [1/FATAL] [tML]: Game ran out of memory. You'll have to find which mod is consuming lots of memory, and contact the devs or remove it.

And then the error pops up

### Steps to reproduce
Using win+tab to swtich between the game and other tabs opened. Then switch back into the game.

### Expected behavior 
It was normal before, the window still resizes before entering full screen and I can use win+tab whenever I want, even in multiplayer. It's just after the most recent update, this issue keeps occuring.

### Actual behavior
crash

### Reproduction frequency
Sometimes it's guaranteed , sometimes it doesn't crash at all.

### Additional Information
No, it just happens all the time.

Lastly, I do wanna know if it's actually my pc and do I have to update my drivers.

edit: this also happens when i accidentally press the win key (only the win key nothing else)

and it seems that when the error pops up the game's resolution is at like 800x600 or something

**Comment by Chicken-Bones** [comment]
Support for tModLoader 1.3 has ended. Please come to the Discord for support if you continue to have issues with tML 1.4
