### ISSUE TITLE
[1.4] ModConfig: changing configs using the "<" and ">" buttons is buggy

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1589]
### Description
Two similar bugs regarding the < and > buttons:
1. [Video](https://cdn.discordapp.com/attachments/445276626352209920/856262496271466556/config.webm) In the main menu config screen: Pressing any arrow softlocks the game, while changing the resolution repeatedly.
2. In the ingame config screen: Pressing any arrow does not do anything at all.

### Log file
No errors in the log.

### Steps to reproduce
Have a mod with atleast two ModConfigs (dont know if you need a field/property in them to count as suitable configs), try swapping them using the keys

**Comment by Pop000100** [comment]
I received this message when switching config sections regardless of the mod as long has two sections.

```
[18:25:41] [Main Thread/ERROR] [Terraria]: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Terraria.ModLoader.Config.UI.UIModConfig.NextConfig(UIMouseEvent evt, UIElement listeningElement)
   at Terraria.UI.UIElement.Click(UIMouseEvent evt)
   at Terraria.UI.UserInterface.Update(GameTime time)
   at Terraria.Main.UpdateUIStates(GameTime gameTime)
   at Terraria.Main.DoUpdate(GameTime& gameTime)
   at Terraria.Main.Update(GameTime gameTime)
```
