### ISSUE TITLE
[1.4] FNA3D error in tModLoader compilation

### ISSUE THREAD

**Issue by IndiiSkies** [tModLoader/tModLoader#1628]
### Description
Nothing but errors building 1.4 so far. tModLoader is complaining about  "System.TypeLoadException: Could not load type 'Microsoft.Xna.Framework.Graphics.FNA3D' from assembly 'ReLogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'."

### File Structure
![FNA3D_DIR](https://user-images.githubusercontent.com/36209245/126690402-4d076cc7-0e89-4caa-a88d-9a36ad2a3179.png)
FNA3D Directory
![TMOD_DIR](https://user-images.githubusercontent.com/36209245/126690667-f1697c5f-ed0c-42b2-a757-8dcb8f120154.png)
tModLoaderDev Directory

### Log File
`[13:03:47] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.2.3+0.12-HEAD-dev-HEAD-5249311756254244486
[13:03:47] [Main Thread/INFO] [tML]: Log date: 7/22/2021
[13:03:47] [Main Thread/INFO] [tML]: Running on Windows NetCore 5.0.7
[13:03:47] [Main Thread/INFO] [tML]: Executable: C:\Program Files (x86)\Steam\steamapps\common\tModLoaderDev\tModLoader.dll
[13:03:47] [Main Thread/INFO] [tML]: Working Directory: C:\Program Files (x86)\Steam\steamapps\common\tModLoaderDev
[13:03:47] [Main Thread/INFO] [tML]: Launch Parameters: 
[13:03:48] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=21.6.0.0, Culture=neutral, PublicKeyToken=null -> FNA3D
[13:03:48] [Main Thread/DEBUG] [tML]: 	attempting load C:\Program Files (x86)\Steam\steamapps\common\tModLoaderDev\Libraries\Native\Windows\FNA3D.dll
[13:03:48] [Main Thread/DEBUG] [tML]: 	success
[13:03:48] [Main Thread/INFO] [tML]: Checking Steam installation...
[13:03:48] [Main Thread/DEBUG] [tML]: Native Resolve: Steamworks.NET, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null -> steam_api
[13:03:48] [Main Thread/DEBUG] [tML]: 	attempting load C:\Program Files (x86)\Steam\steamapps\common\tModLoaderDev\Libraries\Native\Windows\steam_api64.dll
[13:03:48] [Main Thread/DEBUG] [tML]: 	success
[13:03:49] [Main Thread/INFO] [tML]: Steam installation OK.
[13:03:49] [Main Thread/INFO] [Terraria]: Found Terraria steamapp install at: C:\Program Files (x86)\Steam\steamapps\common\Terraria
[13:03:49] [Main Thread/INFO] [Terraria]: Steam Cloud Quota: 120.9 MB available
[13:03:49] [Main Thread/INFO] [FNA]: FNA3D Driver: D3D11
[13:03:49] [Main Thread/INFO] [FNA]: D3D11 Adapter: NVIDIA GeForce GTX 1060 3GB
[13:03:49] [Main Thread/DEBUG] [Terraria]: Device Created, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: Reach, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[13:03:49] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: Reach, Width: 800, Height: 480 -> 720, Fullscreen: False, Display: \\.\DISPLAY1
[13:03:49] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=21.6.0.0, Culture=neutral, PublicKeyToken=null -> FAudio
[13:03:49] [Main Thread/DEBUG] [tML]: 	attempting load C:\Program Files (x86)\Steam\steamapps\common\tModLoaderDev\Libraries\Native\Windows\FAudio.dll
[13:03:49] [Main Thread/DEBUG] [tML]: 	success
[13:03:51] [15/WARN] [tML]: Silently Caught Exception: 
System.TypeLoadException: Could not load type 'Microsoft.Xna.Framework.Graphics.FNA3D' from assembly 'ReLogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCore30Platform.CompileMethodHook(IntPtr jit, IntPtr corJitInfo, CORINFO_METHOD_INFO& methodInfo, UInt32 flags, Byte*& nativeEntry, UInt64& nativeSizeOfCode)
   at System.Runtime.CompilerServices.RuntimeHelpers._PrepareMethod(IRuntimeMethodInfo method, IntPtr* pInstantiation, Int32 cInstantiation)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandle method)
   at Terraria.Program.ForceJITOnMethod(MethodInfo method) in tModLoader\Terraria\Program.TML.cs:line 25
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[13:03:51] [9/WARN] [tML]: Silently Caught Exception: 
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not load type 'Microsoft.Xna.Framework.Graphics.FNA3D' from assembly 'ReLogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.))
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Terraria.Program.ForceLoadAssembly(Assembly assembly, Boolean initializeStaticMembers) in tModLoader\Terraria\Program.cs:line 89
   at Terraria.Program.ForceLoadThread(Object threadContext) in tModLoader\Terraria\Program.cs:line 58
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

[13:03:51] [9/WARN] [tML]: Silently Caught Exception: 
System.AggregateException: One or more errors occurred. (Could not load type 'Microsoft.Xna.Framework.Graphics.FNA3D' from assembly 'ReLogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.)
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Terraria.Program.ForceLoadAssembly(Assembly assembly, Boolean initializeStaticMembers) in tModLoader\Terraria\Program.cs:line 89
   at Terraria.Program.ForceLoadThread(Object threadContext) in tModLoader\Terraria\Program.cs:line 58
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

[13:03:51] [9/ERROR] [tML]: Unhandled Exception
System.AggregateException: One or more errors occurred. (Could not load type 'Microsoft.Xna.Framework.Graphics.FNA3D' from assembly 'ReLogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.)
 ---> System.TypeLoadException: Could not load type 'Microsoft.Xna.Framework.Graphics.FNA3D' from assembly 'ReLogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.CompilerServices.RuntimeHelpers._PrepareMethod(IRuntimeMethodInfo method, IntPtr* pInstantiation, Int32 cInstantiation)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandle method)
   at Terraria.Program.ForceJITOnMethod(MethodInfo method) in tModLoader\Terraria\Program.TML.cs:line 25
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Terraria.Program.ForceLoadAssembly(Assembly assembly, Boolean initializeStaticMembers) in tModLoader\Terraria\Program.cs:line 89
   at Terraria.Program.ForceLoadThread(Object threadContext) in tModLoader\Terraria\Program.cs:line 58
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
`
[client.log](https://github.com/tModLoader/tModLoader/files/6864461/client.log)

**Comment by Solxanich** [comment]
A couple of comments:
- the contents of TmodLoaderDev don't appear to match the same results of the automatic builds in Github Actions, specifically the FNA files.
- are you building using an IDE or via the scripts? Which one?
- there has been some issues in Visual Studio raised already with a workaround here: #1625

**Comment by IndiiSkies** [comment]
It turns out the I needed to use the FNA files from the GitHub repo not from their official website.
