### ISSUE TITLE
[1.4] linux server issues

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1632]
### Description
Headless CentOS server fails to launch fully.
Two errors listed.

Appears to have been broken since Net5 merge

### Log file

1) 
[11:03:27] [Main Thread/DEBUG] [tML]:     attempting load /home/user/tmodloadertest/Libraries/Native/Linux/libFNA3D.so.0
[11:03:27] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.DllNotFoundException: Unable to load shared library 'FNA3D' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libFNA3D: cannot open shared object file: No such file or directory
   at Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_HookLogFunctions(FNA3D_LogFunc info, FNA3D_LogFunc warn, FNA3D_LogFunc error)
   at Microsoft.Xna.Framework.FNALoggerEXT.Initialize()
   at Microsoft.Xna.Framework.FNAPlatform..cctor()
   at Microsoft.Xna.Framework.Game..ctor()
   at Terraria.Main..ctor() in tModLoader\Terraria\Main.cs:line 4877
   at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 193
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 176
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 49

2)
https://media.discordapp.net/attachments/445276626352209920/868064276953313290/unknown.png

### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

### Additional Information
Dire's friend just tried running the builds Ive been sending him on his own client (not the headless server) and it runs there (if steam is on), both client and server (mono versions are almost the same, client 6.12.0, server 6.12.0.107)

I had reproduced the original error posted on Windows by forcing TryLoad() in MonoLaunch ResolveNativeAssemblies to false.
From there, the empty IntPtr would be used down the road and toss the error.
If we really want to narrow down properly, I would highly recommend actually tossing an error if TryLoad fails and thus a Native is failing to load.

**Comment by Mirsario** [comment]
Fixed with recent series of commits.
