### ISSUE TITLE
tMODLOADER mod browser guild

### ISSUE THREAD

**Issue by FF18min** [tModLoader/tModLoader#1647]
tMODLOADER mod browser guild keep ask to update to new version, it makes me cant download new mod, but I already have the newest version

**Comment by Chik3r** [comment]
Can you post your `client.log` file?

> We need log files to help you. You'll find the log files in the logs folder. Look for `client.log`. (NOT the `.zip` file, the file named `client` or `client.log`) 
> Windows Logs: `%UserProfile%\Documents\My Games\Terraria\ModLoader\Logs` (This is typically found `in C:\Documents\`)
> Linux Logs: `~/.local/share/Terraria/ModLoader/Logs/` or `$XDG_DATA_HOME/Terraria/ModLoader/Logs/`
> Mac Logs: `~/Library/Application support/Terraria/ModLoader/Logs/`

**Comment by FF18min** [comment]
[21:26:42] [1/INFO] [tML]: Starting tModLoader v0.11.8.4 Windows client (7/31/2021)
[21:26:42] [1/INFO] [tML]: Running on NetFramework 4.8
[21:26:42] [1/INFO] [tML]: Executable: C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader.exe
[21:26:42] [1/INFO] [tML]: Working Directory: C:\Program Files (x86)\Steam\steamapps\common\tModLoader
[21:26:42] [1/INFO] [tML]: Launch Parameters: 
[21:26:42] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[21:26:42] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[21:26:42] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:26:42] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[21:26:42] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[21:26:42] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[21:26:42] [1/INFO] [tML]: Checking Steam installation...
[21:26:42] [1/INFO] [tML]: Steam installation OK.
[21:26:42] [1/INFO] [Terraria]: Found Terraria steamapp install at: C:\Program Files (x86)\Steam\steamapps\common\Terraria
[21:26:42] [1/INFO] [Terraria]: Steam Cloud Quota: 50.0 MB available
[21:26:43] [1/DEBUG] [Terraria]: Graphics Device: NVIDIA GeForce RTX 3060 Ti {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
[21:26:43] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach -> HiDef, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[21:26:44] [1/INFO] [Terraria]: Loaded 1000 vanilla assets
[21:26:44] [1/INFO] [Terraria]: Loaded 2000 vanilla assets
[21:26:44] [1/INFO] [Terraria]: Loaded 3000 vanilla assets
[21:26:44] [1/INFO] [Terraria]: Loaded 4000 vanilla assets
[21:26:44] [1/INFO] [Terraria]: Loaded 5000 vanilla assets
[21:26:45] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 800 -> 720, Height: 480, Fullscreen: False -> True, Display: \\.\DISPLAY1
[21:26:46] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 720 -> 1920, Height: 480 -> 1080, Fullscreen: True, Display: \\.\DISPLAY1
[21:26:47] [16/DEBUG] [tML]: Assembly Resolve:  -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[21:26:47] [16/DEBUG] [tML]: Assembly Resolve:  -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[21:26:47] [21/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:26:47] [18/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Pdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:26:47] [7/INFO] [Terraria]: JIT loading finished
[21:26:50] [19/INFO] [tML]: Unloading mods
[21:26:50] [19/INFO] [tML]: 查找模组...
[21:26:51] [19/INFO] [tML]: 增容中: !Localizer
[21:26:51] [19/INFO] [tML]: 增容中: Antisocial
[21:26:51] [19/INFO] [tML]: 增容中: CalamityMod
[21:26:51] [19/INFO] [tML]: 增容中: CalamityModMusic
[21:26:51] [19/INFO] [tML]: 增容中: LansUnlimitedBuffSlots
[21:26:51] [19/INFO] [tML]: 初始化...
[21:26:51] [19/DEBUG] [tML]: Assembly Resolve: Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> !Localizer_Ninject_0, Version=3.3.4.0, Culture=neutral, PublicKeyToken=c7192dc5380945e7
[21:26:51] [19/DEBUG] [tML]: Assembly Resolve: Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> !Localizer_Squid_0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[21:26:51] [19/DEBUG] [tML]: Assembly Resolve: Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> !Localizer_0Harmony_0, Version=1.2.0.1, Culture=neutral, PublicKeyToken=null
[21:26:51] [19/INFO] [Localizer]: Loading config
[21:26:51] [19/INFO] [Localizer]: Config loaded
[21:26:52] [19/INFO] [Localizer]: Importer: [Localizer.Package.Import.BasicImporterPostContentLoad`1[[Localizer.DataModel.Default.BasicItemFile, Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]] registered for file type: [Localizer.DataModel.Default.BasicItemFile].
[21:26:52] [19/INFO] [Localizer]: Importer: [Localizer.Package.Import.BasicImporterPostContentLoad`1[[Localizer.DataModel.Default.BasicNPCFile, Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]] registered for file type: [Localizer.DataModel.Default.BasicNPCFile].
[21:26:52] [19/INFO] [Localizer]: Importer: [Localizer.Package.Import.BasicImporterPostContentLoad`1[[Localizer.DataModel.Default.BasicBuffFile, Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]] registered for file type: [Localizer.DataModel.Default.BasicBuffFile].
[21:26:52] [19/INFO] [Localizer]: Importer: [Localizer.Package.Import.BasicImporterPostContentLoad`1[[Localizer.DataModel.Default.BasicProjectileFile, Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]] registered for file type: [Localizer.DataModel.Default.BasicProjectileFile].
[21:26:52] [19/INFO] [Localizer]: Importer: [Localizer.Package.Import.BasicImporterPostContentLoad`1[[Localizer.DataModel.Default.BasicPrefixFile, Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]] registered for file type: [Localizer.DataModel.Default.BasicPrefixFile].
[21:26:52] [19/INFO] [Localizer]: Importer: [Localizer.Package.Import.CustomModTranslationImporter] registered for file type: [Localizer.DataModel.Default.CustomModTranslationFile].
[21:26:52] [19/INFO] [Localizer]: Importer: [Localizer.Package.Import.CecilLdstrImporter] registered for file type: [Localizer.DataModel.Default.LdstrFile].
[21:26:52] [19/INFO] [Localizer]: Updater: [Localizer.Package.Update.BasicFileUpdater`1[[Localizer.DataModel.Default.BasicItemFile, Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]] registered for file type: [Localizer.DataModel.Default.BasicItemFile].
[21:26:52] [19/INFO] [Localizer]: Updater: [Localizer.Package.Update.BasicFileUpdater`1[[Localizer.DataModel.Default.BasicNPCFile, Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]] registered for file type: [Localizer.DataModel.Default.BasicNPCFile].
[21:26:52] [19/INFO] [Localizer]: Updater: [Localizer.Package.Update.BasicFileUpdater`1[[Localizer.DataModel.Default.BasicBuffFile, Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]] registered for file type: [Localizer.DataModel.Default.BasicBuffFile].
[21:26:52] [19/INFO] [Localizer]: Updater: [Localizer.Package.Update.BasicFileUpdater`1[[Localizer.DataModel.Default.BasicProjectileFile, Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]] registered for file type: [Localizer.DataModel.Default.BasicProjectileFile].
[21:26:52] [19/INFO] [Localizer]: Updater: [Localizer.Package.Update.BasicFileUpdater`1[[Localizer.DataModel.Default.BasicPrefixFile, Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]] registered for file type: [Localizer.DataModel.Default.BasicPrefixFile].
[21:26:52] [19/INFO] [Localizer]: Updater: [Localizer.Package.Update.CustomModTranslationUpdater] registered for file type: [Localizer.DataModel.Default.CustomModTranslationFile].
[21:26:52] [19/INFO] [Localizer]: Updater: [Localizer.Package.Update.LdstrFileUpdater] registered for file type: [Localizer.DataModel.Default.LdstrFile].
[21:26:52] [19/INFO] [Localizer]: Patching ModBrowser, tML version: 0.11.8.4
[21:26:52] [19/INFO] [Localizer]: PopulateModBrowser Patched
[21:26:52] [19/INFO] [Localizer]: FromJson Patched
[21:26:52] [19/INFO] [Localizer]: OnActivate Patched
[21:26:52] [19/WARN] [tML]: 静默捕获异常: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Localizer.Utils.Patch(HarmonyInstance instance, String class, String method, Boolean exactMatch, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler)
   at Localizer.ModBrowser.Patches.Patch()
   at Localizer.Localizer.Init()
   at Localizer.Localizer..ctor()
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Terraria.ModLoader.Core.AssemblyManager.Instantiate(LoadedMod mod)
   at Terraria.ModLoader.Core.AssemblyManager.<>c__DisplayClass10_0.<InstantiateMods>b__1(LoadedMod mod)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(List`1 modsToLoad, CancellationToken token)
   at Terraria.ModLoader.Core.ModOrganizer.LoadMods(CancellationToken token)
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token)
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass42_0.<BeginLoad>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[21:26:52] [19/INFO] [Localizer]: ModBrowser Patch exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Localizer.Utils.Patch(HarmonyInstance instance, String class, String method, Boolean exactMatch, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler)
   at Localizer.ModBrowser.Patches.Patch()
[21:26:52] [19/INFO] [Localizer]: SetupDownloadRequest Patched
[21:26:52] [19/INFO] [Localizer]: Early auto import for mod: [Antisocial]
[21:26:52] [19/INFO] [Localizer]: Clearing import queue...
[21:26:52] [19/INFO] [Localizer]: Cleared.
[21:26:52] [19/INFO] [Localizer]: Begin importing
[21:26:52] [19/INFO] [Localizer]: Early auto import for mod: [CalamityMod]
[21:26:52] [19/INFO] [Localizer]: Clearing import queue...
[21:26:52] [19/INFO] [Localizer]: Cleared.
[21:26:52] [19/INFO] [Localizer]: Begin importing
[21:26:52] [19/INFO] [Localizer]: Importing Mod: [CalamityMod]
[21:26:52] [19/DEBUG] [tML]: Assembly Resolve: Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:26:52] [19/WARN] [tML]: Upgraded Reference Mono.Cecil -> Version=0.11.2.0 -> 0.11.3.0
[21:26:52] [19/DEBUG] [tML]: Assembly Resolve: Localizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null
[21:26:52] [19/WARN] [tML]: Upgraded Reference MonoMod.Utils -> Version=20.5.14.1 -> 20.11.16.1
[21:27:00] [19/INFO] [Localizer]: Early auto import for mod: [CalamityModMusic]
[21:27:00] [19/INFO] [Localizer]: Clearing import queue...
[21:27:00] [19/INFO] [Localizer]: Cleared.
[21:27:00] [19/INFO] [Localizer]: Begin importing
[21:27:00] [19/INFO] [Localizer]: Early auto import for mod: [LansUnlimitedBuffSlots]
[21:27:00] [19/INFO] [Localizer]: Clearing import queue...
[21:27:00] [19/INFO] [Localizer]: Cleared.
[21:27:00] [19/INFO] [Localizer]: Begin importing
[21:27:00] [19/INFO] [tML]: 初始化: ModLoader v0.11.8.4
[21:27:00] [19/INFO] [tML]: 初始化: !Localizer v1.5.0.19
[21:27:00] [19/INFO] [tML]: 初始化: Antisocial v1.2.1
[21:27:00] [19/DEBUG] [tML]: Assembly Resolve: Antisocial_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[21:27:00] [19/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[21:27:00] [19/WARN] [tML]: Upgraded Reference MonoMod.RuntimeDetour -> Version=19.12.19.1 -> 20.11.16.1
[21:27:00] [19/DEBUG] [tML]: Hook On.Terraria.UI.ItemSlot::MouseHover(Item[], int, int) added by Antisocial_0
[21:27:00] [19/INFO] [tML]: 初始化: CalamityMod v1.4.5.7
[21:27:03] [19/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[21:27:03] [19/WARN] [tML]: Upgraded Reference MonoMod.Utils -> Version=19.12.19.1 -> 20.11.16.1
[21:27:03] [19/DEBUG] [tML]: Hook IL.Terraria.Wiring::HitWireSingle(int, int) modified by CalamityMod_1
[21:27:04] [19/DEBUG] [tML]: Hook On.Terraria.Main::InitLifeBytes() added by CalamityMod_1
[21:27:04] [19/DEBUG] [tML]: Hook On.Terraria.NPC::SlimeRainSpawns(int) added by CalamityMod_1
[21:27:04] [19/DEBUG] [tML]: Hook IL.Terraria.WorldGen::MakeDungeon(int, int) modified by CalamityMod_1
[21:27:04] [19/DEBUG] [tML]: Hook IL.Terraria.WorldGen::GrowLivingTree(int, int) modified by CalamityMod_1
[21:27:04] [19/DEBUG] [tML]: Hook On.Terraria.WorldGen::OpenDoor(int, int, int) added by CalamityMod_1
[21:27:04] [19/DEBUG] [tML]: Hook On.Terraria.WorldGen::CloseDoor(int, int, bool) added by CalamityMod_1
[21:27:04] [19/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime() modified by CalamityMod_1
[21:27:04] [19/DEBUG] [tML]: Hook On.Terraria.Main::UpdateTime_SpawnTownNPCs() added by CalamityMod_1
[21:27:04] [19/INFO] [tML]: 初始化: CalamityModMusic v1.4.5.3
[21:27:04] [19/INFO] [tML]: 初始化: LansUnlimitedBuffSlots v0.2.1
[21:27:04] [19/INFO] [tML]: 安装中...
[21:27:04] [19/INFO] [tML]: 加载中: ModLoader v0.11.8.4
[21:27:04] [19/INFO] [tML]: 加载中: !Localizer v1.5.0.19
[21:27:04] [19/INFO] [tML]: 加载中: Antisocial v1.2.1
[21:27:04] [19/INFO] [tML]: 加载中: CalamityMod v1.4.5.7
[21:27:04] [26/DEBUG] [tML]: Web Request: https://api.github.com/repos/chi-rei-den/Localizer/releases/latest
[21:27:05] [19/INFO] [CalamityMod]: 检测到ModLoader版本 > 0.11.7.7。Mechworm UUID解决方案已禁用。
[21:27:05] [19/INFO] [tML]: 加载中: CalamityModMusic v1.4.5.3
[21:27:05] [19/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateAudio() modified by CalamityModMusic_0
[21:27:05] [19/INFO] [tML]: 加载中: LansUnlimitedBuffSlots v0.2.1
[21:27:05] [19/INFO] [tML]: RAM usage: 1.9 GB
[21:27:05] [19/INFO] [tML]: 添加合成配方...
[21:27:06] [19/INFO] [Localizer]: Late auto import begin.
[21:27:06] [19/INFO] [Localizer]: Clearing import queue...
[21:27:06] [19/INFO] [Localizer]: Cleared.
[21:27:06] [19/INFO] [Localizer]: Begin importing
[21:27:06] [19/INFO] [Localizer]: Importing Mod: [CalamityMod]
[21:27:06] [19/INFO] [Localizer]: Cleaning item caches, count: 8542
[21:27:06] [19/INFO] [Localizer]: Item caches cleaned. count: 6267, take 0.0330726 seconds
[21:27:06] [19/INFO] [Localizer]: Rebuilding tooltips, count: 6267
[21:27:06] [19/INFO] [Localizer]: Rebuilding completed. count: 6267, take 0.0005742 seconds
[21:27:07] [14/DEBUG] [tML]: Web Request: https://mirror.sgkoi.dev/tModLoader/listmods.php
[21:27:07] [46/DEBUG] [tML]: Web Request: http://mirror7.sgkoi.dev/tModLoader/listmods.php
[21:27:09] [1/DEBUG] [tML]: Web Request: https://mirror7.sgkoi.dev/direct/BetterRecipe.png
[21:27:09] [1/DEBUG] [tML]: Web Request: https://mirror7.sgkoi.dev/direct/SagesMania.png
[21:27:12] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "https://github.com/tModLoader/tModLoader/releases/latest" 
[21:27:50] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1080, Fullscreen: True, Display: \\.\DISPLAY1
[21:27:54] [3/INFO] [Terraria]: Loading World: kami's world, IsCloud=True
[21:27:54] [3/INFO] [StatusText]: 正在重置游戏物品
[21:27:55] [3/INFO] [StatusText]: 正在加载世界数据：
[21:27:56] [3/INFO] [StatusText]: 正在安置液体
[21:27:58] [3/INFO] [StatusText]: 正在加载地图数据：
[21:27:58] [3/INFO] [StatusText]: 正在绘制地图：
[21:27:58] [1/INFO] [Terraria]: Entering world with player: 神的意志, IsCloud=True
[21:30:02] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1080, Fullscreen: True, Display: \\.\DISPLAY1
[21:31:49] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1080, Fullscreen: True, Display: \\.\DISPLAY1
[21:34:55] [1/INFO] [Terraria]: Loaded 6000 vanilla assets
[21:36:47] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1080, Fullscreen: True, Display: \\.\DISPLAY1
[21:37:08] [1/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateAudio() modified by CalamityModMusic_0
[21:37:08] [38/INFO] [StatusText]: 正在保存地图数据：
[21:37:09] [38/INFO] [StatusText]: 正在保存世界数据：
[21:37:09] [38/INFO] [StatusText]: 正在验证世界保存数据：
[21:37:18] [41/INFO] [StatusText]: 正在释放未用资源
[21:37:18] [41/INFO] [StatusText]: 正在重置游戏物品
[21:37:18] [41/INFO] [Terraria]: Generating World: 123
[21:37:25] [41/INFO] [StatusText]: 正在创建地狱
[21:37:26] [41/INFO] [StatusText]: 正在创建地牢
[21:37:28] [41/INFO] [StatusText]: 正在安置液体
[21:37:37] [41/INFO] [StatusText]: 正在保存世界数据：
[21:37:37] [41/INFO] [StatusText]: 正在验证世界保存数据：
[21:37:57] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1080, Fullscreen: True, Display: \\.\DISPLAY1
[21:37:59] [45/INFO] [Terraria]: Loading World: 123, IsCloud=False
[21:37:59] [45/INFO] [StatusText]: 正在重置游戏物品
[21:37:59] [45/INFO] [StatusText]: 正在加载世界数据：
[21:37:59] [45/INFO] [StatusText]: 正在安置液体
[21:37:59] [1/INFO] [Terraria]: Entering world with player: 神的意志, IsCloud=True
[21:38:50] [3/INFO] [StatusText]: 正在保存世界数据：
[21:38:50] [3/INFO] [StatusText]: 正在验证世界保存数据：
[21:48:50] [42/INFO] [StatusText]: 正在保存世界数据：
[21:48:50] [42/INFO] [StatusText]: 正在验证世界保存数据：
[21:51:53] [1/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateAudio() modified by CalamityModMusic_0
[21:51:53] [39/INFO] [StatusText]: 正在保存地图数据：
[21:51:53] [39/INFO] [StatusText]: 正在保存世界数据：
[21:51:53] [39/INFO] [StatusText]: 正在验证世界保存数据：
[21:51:56] [41/INFO] [Terraria]: Loading World: kami's world, IsCloud=True
[21:51:56] [41/INFO] [StatusText]: 正在重置游戏物品
[21:51:58] [41/INFO] [StatusText]: 正在加载世界数据：
[21:51:58] [41/INFO] [StatusText]: 正在安置液体
[21:51:59] [41/INFO] [StatusText]: 正在加载地图数据：
[21:51:59] [41/INFO] [StatusText]: 正在绘制地图：
[21:51:59] [1/INFO] [Terraria]: Entering world with player: 神的意志, IsCloud=True
[21:52:12] [1/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateAudio() modified by CalamityModMusic_0
[21:52:12] [40/INFO] [StatusText]: 正在保存地图数据：
[21:52:13] [40/INFO] [StatusText]: 正在保存世界数据：
[21:52:14] [40/INFO] [StatusText]: 正在验证世界保存数据：

**Comment by FF18min** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/6912083/client.log)

**Comment by wushuangliu070** [comment]
I have met the same problem

**Comment by wushuangliu070** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/6912367/client.log)

**Comment by sgkoishi** [comment]
#### There's nothing to do with tModLoader.
I believe it's a Localizer problem: the mirror site is temporarily down (ran out of bandwidth) and I add a 302 redirect to another site; which is kinda buggy (not too sure why; the only thing I know is that the Internet connection of that server is heavily cached incorrectly).
Everything will automatically be back after ~1 week; please close this issue safely. In case anyone else asks the same/similar problem, please post the link to this comment.

<hr>

@FF18min @wushuangliu070 
这是个和汉化者有关的问题：汉化者的主镜像网站因流量用光而暂时挂了。你可以从以下操作中任选一种或多种：
* 打开配置文件，把写着`mirror.sgkoi.dev`的mirror改成mirror8、9或10。请自行测试哪个更加有效。
* 打开镜像网站并手动下载安装模组。
* 稍等一段时间，镜像将在一周内恢复；什么都不用做。
* 我或许会在更早之前修好这个问题；什么都不用做。
