### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Official-Skurn** [tModLoader/tModLoader#1725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

After deleting all terraria and tmodloader related files and doing a fresh install I get the following error upon launching tmodloader alpha

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/6970915/client.log)

[12:04:22] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.2.3+0.12-1.4-Alpha-1a47bc4312f7ecb227e497c564b5fbd4b7ff54d8-5249328808059736824
[12:04:22] [Main Thread/INFO] [tML]: Log date: 8/11/2021
[12:04:22] [Main Thread/INFO] [tML]: Running on Windows X64 NetCore 5.0.8
[12:04:22] [Main Thread/INFO] [tML]: Executable: C:\Steam Games\steamapps\common\tModLoader\tModLoader.dll
[12:04:22] [Main Thread/INFO] [tML]: Working Directory: C:\Steam Games\steamapps\common\tModLoader
[12:04:22] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=21.8.0.0, Culture=neutral, PublicKeyToken=null -> FNA3D
[12:04:22] [Main Thread/DEBUG] [tML]: 	attempting load C:\Steam Games\steamapps\common\tModLoader\Libraries\Native\Windows\FNA3D.dll
[12:04:23] [Main Thread/DEBUG] [tML]: 	success
[12:04:23] [Main Thread/INFO] [tML]: Checking Steam installation...
[12:04:23] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.EntryPointNotFoundException: Unable to find an entry point named 'SteamAPI_ISteamClient_GetISteamRemotePlay' in DLL 'steam_api64'.
   at Steamworks.NativeMethods.ISteamClient_GetISteamRemotePlay(IntPtr instancePtr, HSteamUser hSteamUser, HSteamPipe hSteamPipe, UTF8StringHandle pchVersion)
   at Steamworks.SteamClient.GetISteamRemotePlay(HSteamUser hSteamUser, HSteamPipe hSteamPipe, String pchVersion)
   at Steamworks.CSteamAPIContext.Init()
   at Steamworks.SteamAPI.Init()
   at Terraria.ModLoader.Engine.Steam..cctor()
   at Terraria.Social.Steam.CoreSocialModule.Initialize()
   at Terraria.Social.SocialAPI.LoadSteam()
   at Terraria.ModLoader.Engine.InstallVerifier.CheckSteam()
   at Terraria.ModLoader.Engine.InstallVerifier.InstallCheck()
   at Terraria.ModLoader.Engine.InstallVerifier.get_IsValid()
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode)
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at MonoLaunch.Main(String[] args)

[12:04:23] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.TypeInitializationException: The type initializer for 'Terraria.ModLoader.Engine.Steam' threw an exception.
   at Terraria.Social.Steam.CoreSocialModule.Initialize()
   at Terraria.Social.SocialAPI.LoadSteam()
   at Terraria.ModLoader.Engine.InstallVerifier.CheckSteam()
   at Terraria.ModLoader.Engine.InstallVerifier.InstallCheck()
   at Terraria.ModLoader.Engine.InstallVerifier.get_IsValid()
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode)
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at MonoLaunch.Main(String[] args)

[12:04:23] [Main Thread/FATAL] [Terraria]: Main engine crash
System.TypeInitializationException: The type initializer for 'Terraria.ModLoader.Engine.Steam' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'SteamAPI_ISteamClient_GetISteamRemotePlay' in DLL 'steam_api64'.
   at Steamworks.NativeMethods.ISteamClient_GetISteamRemotePlay(IntPtr instancePtr, HSteamUser hSteamUser, HSteamPipe hSteamPipe, UTF8StringHandle pchVersion)
   at Steamworks.SteamClient.GetISteamRemotePlay(HSteamUser hSteamUser, HSteamPipe hSteamPipe, String pchVersion)
   at Steamworks.CSteamAPIContext.Init()
   at Steamworks.SteamAPI.Init()
   at Terraria.ModLoader.Engine.Steam..cctor()
   --- End of inner exception stack trace ---
   at Terraria.Social.Steam.CoreSocialModule.Initialize()
   at Terraria.Social.SocialAPI.LoadSteam()
   at Terraria.ModLoader.Engine.InstallVerifier.CheckSteam()
   at Terraria.ModLoader.Engine.InstallVerifier.InstallCheck()
   at Terraria.ModLoader.Engine.InstallVerifier.get_IsValid()
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode)
   at Terraria.Program.LaunchGame_(Boolean isServer)

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
