### ISSUE TITLE
[1.4] Vanilla World Gen Tasks are possible to error due to placing tiles outside the world.

### ISSUE THREAD

**Issue by Zonix-YT** [tModLoader/tModLoader#1865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

When generating worlds Vanilla world gen tasks can attempt to generate something outside the world giving a error you can see in the Log File.

### Log File

In-TML error:
![image](https://user-images.githubusercontent.com/64276800/134433424-68a64531-03e7-4ebb-86bc-87a78a3b3a4c.png)

Log Error:
[00:04:05] [26/ERROR] [tML]: A problem was encountered during world generation
Cactus, Palm Trees, & Coral
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.WorldGen.<>c.<GenerateWorld>b__351_99(GenerationProgress progress, GameConfiguration passConfig) in tModLoader\Terraria\WorldGen.cs:line 11179
   at Terraria.GameContent.Generation.PassLegacy.ApplyPass(GenerationProgress progress, GameConfiguration configuration) in tModLoader\Terraria\GameContent\Generation\PassLegacy.cs:line 226
   at Terraria.WorldBuilding.GenPass.Apply(GenerationProgress progress, GameConfiguration configuration) in tModLoader\Terraria\WorldBuilding\GenPass.cs:line 24
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 47
[00:04:05] [26/WARN] [tML]: Silently Caught Exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 47
   at Terraria.WorldGen.GenerateWorld(Int32 seed, GenerationProgress customProgressObject) in tModLoader\Terraria\WorldGen.cs:line 12092
   at Terraria.WorldGen.do_worldGenCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2341
   at Terraria.WorldGen.worldGenCallback(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2331
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

[00:04:05] [26/ERROR] [Terraria]: A problem was encountered during world generation
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 61
   at Terraria.WorldGen.GenerateWorld(Int32 seed, GenerationProgress customProgressObject) in tModLoader\Terraria\WorldGen.cs:line 12092
   at Terraria.WorldGen.do_worldGenCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2341
   at Terraria.WorldGen.worldGenCallback(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2331
[00:07:30] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "C:\Users\angry\Documents\My Games\Terraria\ModLoader\Beta\Logs" 

### Steps to reproduce

This issue seems to be extremely inconsistent but can just happen at anytime...

### Expected Behavior

This issue should just not happen when generating a world.

### Actual Behavior

Vanilla world gen tasks attempt to can error world gen by attempting to generate a tile of any form outside the world's tile array.

### Reproduction frequency

It can happen 3+ times in a row then go for a few hours+ and return.

### Additional Information

I believe a possible fix for this is to make all functions for placing any tile type checks if it's in the world or not and if it is just don't let that function run that attempt preventing the tile from having a attempt at being generated.

**Comment by Unftf** [comment]
Do you know any (vanilla) world seed which is doing this?

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
