### ISSUE TITLE
Terraria Ambience and some other mods crash the game when sounds play.

### ISSUE THREAD

**Issue by RianQuenlin** [tModLoader/tModLoader#2914]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

If I run Terraria Ambience, I can load into the world until I make a sound, at which point the game immediately freezes then crashes with a not responding error.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9541270/client.log)

### Steps to reproduce

- Load Terraria Ambience as a mod
- Enter a game world
- Do anything that makes a sound, like touching grass or swinging a weapon.
![image](https://user-images.githubusercontent.com/88654233/189498556-591745f8-b04e-493b-9974-f63fc626a9dc.png)

### Expected Behavior

Sounds play accordingly without issue.

### Actual Behavior

Game freezes then crashes with a Not Responding error.

### Reproduction frequency

Consistently. 
If I'm using Terraria Ambience it crashes when a sound should play.
If I'm using Overhaul it crashes upon world load. Overhaul makes extensive use of audio ambience.
if I'm using Calamity it crashes at random points. (not sure if related but one crash happened the exact moment I hit a slime with a wulfrum knife as it was bobbing in water)

### Additional Information

- I've had these crashes happen when only Terraria Ambience or Overhaul were installed on their own. Didn't test with Calamity due to the random nature of the crashes.
- World size is irrelevant.

**Comment by JavidPack** [comment]
We definitely need more information, if you are experiencing this issue, please comment.

**Comment by RianQuenlin** [comment]
Was able to get the error message window to pop up when I checked after the last tmodloader update.

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	dotnet.exe
  Application Version:	6.0.21.52210
  Application Timestamp:	61735065
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.10240.16390
  Fault Module Timestamp:	55a5b718
  Exception Code:	40000015
  Exception Offset:	0000000000065a5f
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	7337
  Additional Information 2:	7337c6ee436eb78bee2ef032c1ee0ded
  Additional Information 3:	974b
  Additional Information 4:	974b714d06f703ce158c3431a4a1ca42
```

While searching the internet for ucrtbase.dll crashes I saw one about disabling the Windows Audio Service under services.msc for No Man's Sky, I tried it and now I get this error.

```
[20:30:02.217] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading TerrariaAmbience v0.2.2.4
It has been detected that this mod was built for tModLoader v2022.7.58.9
However, you are using tModLoader v2022.9.47.4
The mod(s) have been automatically disabled.
ReLogic.Content.AssetLoadException: Asset could not be found: "Sounds\Custom\ambient\biome\forest_morning"
   at ReLogic.Content.AssetRepository.LoadAssetWithPotentialAsync[T](Asset`1 asset, AssetRequestMode mode) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Content\AssetRepository.cs:line 262
   at ReLogic.Content.AssetRepository.SafelyWaitForLoad[T](Asset`1 asset, Task loadTask, Boolean tracked) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Content\AssetRepository.cs:line 307
   at ReLogic.Content.AssetRepository.<>c__DisplayClass45_0`1.<LoadAsset>b__0() in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Content\AssetRepository.cs:line 210
   at ReLogic.Content.AssetRepository.Request[T](String assetName, AssetRequestMode mode) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Content\AssetRepository.cs:line 171
   at TerrariaAmbience.Content.Ambience.Initialize() in TerrariaAmbience\Content\Ambience.cs:line 212
   at TerrariaAmbience.TerrariaAmbience.Load() in TerrariaAmbience.cs:line 88
   at Terraria.ModLoader.ModContent.<>c.<Load>b__42_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 317
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 383
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 310
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 125
[20:30:02.239] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: TerrariaAmbience
[20:30:28.846] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "tModLoader-Logs" 
```

If I re-enable the Windows Audio service, I _don't_ get the error and the problem I have persists. It might be that this is simply incompatible but if Windows Audio service is enabled it doesn't detect it as incompatible for whatever reason.

**Comment by JavidPack** [comment]
That error you have there is probably just a typo in the TerrariaAmbience mod. It looks like tmod is disabling that mod. You aren't getting the freeze in this situation?

I'm not sure what's up with this "Windows Audio Service" thing, but it is good info that hopefully someone can act on.

**Comment by RianQuenlin** [comment]
> It looks like tmod is disabling that mod. You aren't getting the freeze in this situation?
It still freezes, the odd thing is that tmod only disables it if I disable windows audio service.

> I'm not sure what's up with this "Windows Audio Service" thing, but it is good info that hopefully someone can act on.
It's literally what allows Windows to play sound.

**Comment by RianQuenlin** [comment]
Turns out this is an issue with FNA. Setting your sound quality to 16bit 48000hz (DVD Quality) prevents the crash.
![image](https://github.com/tModLoader/tModLoader/assets/88654233/b1afa0e1-5b8f-46a5-b33e-c16039039eb9)

**Comment by steviegt6** [comment]
@RighteousRyan1

**Comment by RighteousRyan1** [comment]
Just now seeing this unfortunately, but yes. FAudio reverb handles cause problems for unexpected frequencies. @RianQuenlin that problem is out of my discretion, so I'd need to PR to FAudio, but I can't really do C that well ¯\_(ツ)_/¯
