### ISSUE TITLE
Wav sound file at _ failed to load

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#308]
```
The wav sound file at Sounds/Item/FlareSound failed to load
   at Terraria.ModLoader.Mod.LoadWav(String path, Byte[] bytes)
   at Terraria.ModLoader.Mod.LoadResourceFromStream(String path, Int32 len, BinaryReader reader)
   at Terraria.ModLoader.IO.TmodFile.Read(LoadedState desiredState, ReadStreamingAsset streamingHandler)
   at Terraria.ModLoader.ModLoader.do_Load(Object threadContext)

Inner Exception:
External component has thrown an exception.
   at Microsoft.Xna.Framework.Audio.SoundEffect.AllocateFormatAndData(Byte[] format, Byte[] data, Int32 offset, Int32 count)
   at Microsoft.Xna.Framework.Audio.SoundEffect..ctor(Stream stream)
   at Microsoft.Xna.Framework.Audio.SoundEffect.FromStream(Stream stream)
   at Terraria.ModLoader.Mod.LoadWav(String path, Byte[] bytes)
```

This error has been around for a while so I thought I'd make an issue for it so we could track it and possibly find a solution.

Basically, if there are no audio devices available, creating sound effects fails in XNA. It appears to be known problem with XNA.

The problem can be fixed by plugging in speakers or headphones.

The problem can be triggered on Windows by opening playback devices and disabling playback devices and then reloading any mod with sounds:

![](https://i.imgur.com/2YmitEZ.png)

Possible Solution: Since the player doesn't have audio anyway, we can skip loading sounds, bypassing the issue. This might lead the mod to an unexpected state, so maybe we'll need to still fill the sound arrays with dummy data somehow.

**Comment by Jofairden** [comment]
> Possible Solution: Since the player doesn't have audio anyway, we can skip loading sounds, bypassing the issue. This might lead the mod to an unexpected state, so maybe we'll need to still fill the sound arrays with dummy data somehow.

This actually seems half-decent, if the problem is embedded in layers of layers... @JavidPack does this problem actually still occur? I haven't seen it pop up lately, but also popup for vanilla. Maybe it got fixed in vanilla?

**Comment by JavidPack** [comment]
I'm pretty sure this is still an issue. It would take an XNA update to fix this.

**Comment by Chicken-Bones** [comment]
https://github.com/blushiemagic/tModLoader/commit/9dc39592927135fe0de2145bdcd7443d054ed1c9
Vanilla already places try-catch around all audio code for this case exactly.
Now skips loading sounds, no dummy data, just nulls everywhere.

**Comment by JavidPack** [comment]
Reportedly, this is not sufficient anymore on 0.11.6.2

**Comment by JavidPack** [comment]
This might be a duplicate of 1.4 specific issues.
