### ISSUE TITLE
Publish disabled mod with icon.png crashes

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#592]
See title.

```
[21:31:36] [1/WARN] [tML]: Silently Caught Exception: 
System.IO.IOException: File not open: D:\Documents\My Games\Terraria\ModLoader\Mods\PublishTest.tmod
   at Terraria.ModLoader.Core.TmodFile.GetStream(FileEntry entry, Boolean newFileStream) in tModLoader\Terraria.ModLoader.Core\TmodFile.cs:line 106
   at Terraria.ModLoader.Core.TmodFile.GetBytes(FileEntry entry) in tModLoader\Terraria.ModLoader.Core\TmodFile.cs:line 92
   at Terraria.ModLoader.Core.TmodFile.GetBytes(String fileName) in tModLoader\Terraria.ModLoader.Core\TmodFile.cs:line 96
   at Terraria.ModLoader.UI.UIModSourceItem.Publish(UIMouseEvent evt, UIElement listeningElement) in tModLoader\Terraria.ModLoader.UI\UIModSourceItem.cs:line 164
   at Terraria.UI.UIElement.Click(UIMouseEvent evt) in tModLoader\Terraria.UI\UIElement.cs:line 410
```

**Comment by Jofairden** [comment]
Huh, it tries to load the icon but since the mod isn't loaded it isn't there? (I did forget, it wasn't part of the .tmod itself?)
