### ISSUE TITLE
Ignore Warning Addition: Terraria.Lighting.doColors

### ISSUE THREAD

**Issue by SheepishShepherd** [tModLoader/tModLoader#602]
The following warning appears whats seemingly at random while playing through. Supposedly a vanilla bug. Issue is for adding this message to the ignore list.

```[17:06:32] [8/WARN] [tML]: Silently Caught Exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.Lighting.doColors_Mode0_Swipe(LightingSwipeData swipeData)
   at Terraria.Lighting.callback_LightingSwipe(Object obj)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Jofairden** [comment]
This has been a confirmed vanilla bug. Hopefully it's gone in 1.4. Thx!
