### ISSUE TITLE
Game crashes when I load into my world

### ISSUE THREAD

**Issue by haldowood** [tModLoader/tModLoader#622]
### Description
I did exactly as the directions gave me, I extracted to a diffent folder to attempt to auto install. My java is up to date (1.8). Whenever I extract, it just makes another folder of the same contents. When I go into terraria everything is fine until I go into my world. it loads up the mods, then goes to my world then crashes the game every time

### Steps to Reproduce

1. get into terraria
2. Press play, on character then world
3. Loads in, then crashes

### Actual behavior
Game crashes when Ioad in.

### Reproduction frequency
every time

### Versions

The tModLoader version 0.11.3 (current)

### Mods
Calamity mod
Mod helpers
wing slot
Precise items
Better taxes

### Additional Information
Here is my crash log from terraria:

7/25/2019 2:11:01 PM
System.DllNotFoundException: Unable to load DLL 'CSteamworks': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(AppId_t unOwnAppID)
   at Terraria.Social.Steam.CoreSocialModule.Initialize()
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode)
   at Terraria.Program.LaunchGame_()

7/25/2019 2:14:05 PM
HamstarHelpers.Components.Errors.HamstarException: Invalid modList
   at HamstarHelpers.Internals.Menus.ModTags.ModBrowserTagsMenuContext.BeginModBrowserPopulateCheck(UIState modBrowserUi)
   at HamstarHelpers.Internals.Menus.ModTags.ModBrowserTagsMenuContext.Show(UIState ui)
   at HamstarHelpers.Services.Menus.MenuContextServiceManager.LoadUI(UIState ui)
   at HamstarHelpers.Services.Menus.MenuContextServiceManager.Update()
   at HamstarHelpers.Services.Menus.MenuContextServiceManager._Update(GameTime gametime)
   at System.Action`1.Invoke(T obj)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()

7/25/2019 2:21:37 PM
HamstarHelpers.Components.Errors.HamstarException: Invalid modList
   at HamstarHelpers.Internals.Menus.ModTags.ModBrowserTagsMenuContext.BeginModBrowserPopulateCheck(UIState modBrowserUi)
   at HamstarHelpers.Internals.Menus.ModTags.ModBrowserTagsMenuContext.Show(UIState ui)
   at HamstarHelpers.Services.Menus.MenuContextServiceManager.LoadUI(UIState ui)
   at HamstarHelpers.Services.Menus.MenuContextServiceManager.Update()
   at HamstarHelpers.Services.Menus.MenuContextServiceManager._Update(GameTime gametime)
   at System.Action`1.Invoke(T obj)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()

7/25/2019 2:39:55 PM
HamstarHelpers.Components.Errors.HamstarException: Invalid modList
   at HamstarHelpers.Internals.Menus.ModTags.ModBrowserTagsMenuContext.BeginModBrowserPopulateCheck(UIState modBrowserUi)
   at HamstarHelpers.Internals.Menus.ModTags.ModBrowserTagsMenuContext.Show(UIState ui)
   at HamstarHelpers.Services.Menus.MenuContextServiceManager.LoadUI(UIState ui)
   at HamstarHelpers.Services.Menus.MenuContextServiceManager.Update()
   at HamstarHelpers.Services.Menus.MenuContextServiceManager._Update(GameTime gametime)
   at System.Action`1.Invoke(T obj)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()

**Comment by haldowood** [comment]
I fixed the issue. I had to disable all of my mods, then I went into mod browser. It gave me the prompt to update mods, which I did. I then enabled my mods and went back into my game. Game works now.

**Comment by Jofairden** [comment]
Yep, it was likely hamstar's mod being outdated but fixed in the newer version.
