### ISSUE TITLE
NoSync flag stuck cliens without mod on Mod Sync if any ModWorld use NetSend

### ISSUE THREAD

**Issue by KindRedSand** [tModLoader/tModLoader#635]
### Description
If mod flagged as `NoSync` and have any `ModWorld` what override `NetSend` method, Client without mod stuck in endless Mod Sync state.

### Steps to Reproduce 

1. Create any empty mod, in `build.txt` set `side = NoSync` , create any ModWorld
2. Override `NetSend` in `ModWorld` and write any data:
```cs
	public override void NetSend(BinaryWriter writer)
        {
            writer.Write(false);
        }
```
3. Start server with mod enabled
4. Connect with client without this mod

### Expected behavior 
All `NetSend` data from `NoSync` mod should be ignored if mod not loaded. It safe with `mod.GetPacket()` but for some reason breaks with `NetSend` 

### Actual behavior
Stucks in world data mod sync

### Reproduction frequency
Each connection attempt without mod

### Versions
tML 0.10.5
tML 0.11.3

### Additional Information
Exapmle `ModWorld`
```cs
using Terraria;
using Terraria.ModLoader;
using System.IO;

namespace Test
{
    public class TestWorld : ModWorld
    {
		public override void NetSend(BinaryWriter writer)
        {
            writer.Write(false);
        }
		
		public override void NetReceive(BinaryReader reader)
		{
			reader.ReadBoolean();
		}
    }
}
```

**Comment by Chicken-Bones** [comment]
NoSync mods are normally prevented from adding content. And I guess it counts in this case. We may be able to fix it though

**Comment by Chicken-Bones** [comment]
Accidentally commited with wrong issue number. Reopening

**Comment by Spiky-73** [comment]
This is also the case with GlobalItem `NetSend` and `NetReceive` with tML v2024.09

I get the following error in the client in [client.log](https://github.com/user-attachments/files/17842733/client.log) when joining a server without the mod:
```
[09:53:02.050] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.IO.IOException: Read underflow 0 of 11 bytes
   at Terraria.ModLoader.IO.BinaryIO.SafeRead(BinaryReader reader, Action`1 read)
   at Terraria.ModLoader.IO.ItemIO.ReceiveModData(Item item, BinaryReader reader)
   at Terraria.ModLoader.IO.ItemIO.Receive(Item item, BinaryReader reader, Boolean readStack, Boolean readFavorite)
   at Terraria.ModLoader.IO.ItemIO.Receive(BinaryReader reader, Boolean readStack, Boolean readFavorite)
   at Terraria.MessageBuffer.GetData(Int32 start, Int32 length, Int32& messageType)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
   at Terraria.Main.DoUpdate(GameTime& gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1()
   at Terraria.MonoLaunch.Main(String[] args)

[09:53:02.050] [Main Thread/ERROR] [tML]: System.IO.IOException: Read underflow 0 of 11 bytes
   at Terraria.ModLoader.IO.BinaryIO.SafeRead(BinaryReader reader, Action`1 read) in tModLoader\Terraria\ModLoader\IO\BinaryIO.cs:line 29
   at Terraria.ModLoader.IO.ItemIO.ReceiveModData(Item item, BinaryReader reader) in tModLoader\Terraria\ModLoader\IO\ItemIO.cs:line 257
[09:53:02.051] [Main Thread/ERROR] [tML]: Above IOException error caused by ItemGuid from the TestMod mod while reading Rod of Harmony.
```

Sample code:
```csharp
using System.IO;
using Terraria;
using Terraria.ModLoader;

namespace TestMod;

public sealed class ItemGuid : GlobalItem {
    public override void NetSend(Item item, BinaryWriter writer) {
    
    }

    public override void NetReceive(Item item, BinaryReader reader) {
    
    }
}
```

**Comment by Chicken-Bones** [comment]
When sending a packet via `Mod.GetPacket` we can drop the entire packet for clients who don't have the mod installed. 

With all other hooks, the data provided by the mod is just part of the packet that will be sent, and we don't have the capacity to generate different packets for different clients. 

We do send the lengths of each of the data segments provided by each class (like `GlobalItem` or `ModWorld`) but the client doesn't know which readers it is missing. The server would need to send the list of readers to clients on connect, and have the clients generate some dummy entries to consume the extra data. 

Unfortunately, this would only work for packets sent from server -> client. For things like `GlobalItem` which are sent both ways, there is no way for a client without the mod installed to provide any data, and at the point the receive hooks are executed we don't have any information about who sent the packet.

**Comment by Spiky-73** [comment]
Would it be possible to use `Mod.NetID` as it's done for `ModPackets` ?

If the mod's `netId` was added 1st (as in `<netID><length+data>`), the hole section could be skipped if the mod is not loaded on the client/server.

**Comment by Chicken-Bones** [comment]
The main issue is that items sent from client who doesn't have the mod to server would cause data loss on those globals

**Comment by Spiky-73** [comment]
In my opinion, if it's a `NoSync` mod the modder should already be aware of this and be OK with it or use the modeSide `Both` if syncing data is mandatory. As the [docs](https://docs.tmodloader.net/docs/1.4-stable/namespace_terraria_1_1_mod_loader.html#a1c82c6b1930a8ee5c45efb091a036b06) says for  `NoSync`: "This is useful if you want optional extra features when both the client and server have this mod."

You could use `Mod.IsNetSynced` on the client to conditionally send data but as it stands today, simply overriding `NetSend` causes a bug and using `Mod.IsNetSynced` is not an option on the server.

In my case I wanted to sync item guids between clients and the server, without it been a necessity for the mod to work properly.
