### ISSUE TITLE
Make TypeLoadException report the type which failed to load and why

### ISSUE THREAD

**Issue by Chicken-Bones** [tModLoader/tModLoader#690]
need to add special logging for this exception type

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Terraria.ModLoader.Core.AssemblyManager.Instantiate(LoadedMod mod)

**Comment by JavidPack** [comment]
Here is how it looks.

![](https://i.imgur.com/BJfda9d.png)

**Comment by Chicken-Bones** [comment]
Need stack trace for LoaderExceptions too

**Comment by JavidPack** [comment]
Stack trace was null for my test setup.
