### ISSUE TITLE
[Bug] Character and world "Corruption" with TagCompound

### ISSUE THREAD

**Issue by Plantterror** [tModLoader/tModLoader#695]
### Description
Having a character or a world with TagCompound data in it will cause any characters and/or worlds with the TagCompound to corrupt when not loading the mod with the TagCompound for the first time. This does not affect reloading in any way, only the initial loading of mods.

### Log File
64 bit variant:
https://cdn.discordapp.com/attachments/537059980042305548/635248560061022237/client.log
```[16:47:59] [1/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.IO.PlayerIO.LoadModData(Player player, IList`1 list)
   at Terraria.ModLoader.IO.PlayerIO.Load(Player player, String path, Boolean isCloudSave)
   at Terraria.Player.LoadPlayer(String playerPath, Boolean cloudSave)
   at Terraria.Player.GetFileData(String file, Boolean cloudSave)
   at Terraria.Main.LoadPlayers()
   at Terraria.GameContent.UI.States.UICharacterSelect.OnActivate()
   at Terraria.UI.UIElement.Activate()
   at Terraria.UI.UserInterface.SetState(UIState state)
   at Terraria.Main.DrawMenu(GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)```
32 bit variant:


### Steps to Reproduce
Create a Character or world with a mod that adjusts TagCompound (tested with Cheat Sheet due to accessory slots). Close the game and reopen. Skip loading mods, and open your character folder. This error will appear and the character resets.

### Expected behavior 
Normally, when a mod isn't loaded it will appear with a warning symbol with the mods that were not loaded compared to the character. A world does not get this warning.

### Actual behavior
The character becomes corrupted to the default look and stats, and becomes unclickable. Loading a world with this effect will proceed to fail.

### Reproduction frequency
100% accuracy. Does not work if you reload mods, it must be from an initial load.

### Additional Information
N/A

**Comment by SamYs94** [comment]
ok nobp

**Comment by Plantterror** [comment]
Okay, I may have been wrong. Deleting enabled.json actually doesn't make this issue. Gonna assume from that that the "Finding Mods" part is faulty from this new information.

**Comment by SamYs94** [comment]
[yes.txt](https://github.com/tModLoader/tModLoader/files/3764692/yes.txt)

**Comment by Chicken-Bones** [comment]
Probably fixed in #702, give it a try

**Comment by Plantterror** [comment]
lmao you closed #702 right after referencing it

But yeah, that's the exact issue I have, holding cancel on the main menu skips loading Modloader and TagCompound ends up not referenced, which causes characters and worlds to freak out.

**Comment by Plantterror** [comment]
Closing this one since the other issue got a fix in the next update.
