### ISSUE TITLE
Mod browser not loading

### ISSUE THREAD

**Issue by yabbyshabby** [tModLoader/tModLoader#696]
When i open the browser it load for 1-2 minutes and says its offline. It's been doing this for about 3 days. I'm also using latest version.
[client.log](https://github.com/tModLoader/tModLoader/files/3747367/client.log)
[server.log](https://github.com/tModLoader/tModLoader/files/3747368/server.log)

[20:42:53] [1/INFO] [tML]: Starting tModLoader v0.11.5 Windows client
[20:42:53] [1/INFO] [tML]: Running on NetFramework 4.7.2
[20:42:53] [1/INFO] [tML]: Executable: D:\Program Files\Steam\steamapps\common\Terraria\Terraria.exe
[20:42:53] [1/INFO] [tML]: Working Directory: D:\Program Files\Steam\steamapps\common\Terraria
[20:42:53] [1/INFO] [tML]: Launch Parameters: 
[20:42:53] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=19.10.5.2, Culture=neutral, PublicKeyToken=null
[20:42:53] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=19.10.5.2, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=19.10.5.2, Culture=neutral, PublicKeyToken=null
[20:42:53] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=19.10.5.2, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.10.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[20:42:53] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[20:42:53] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[20:42:55] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[20:42:55] [1/DEBUG] [Terraria]: Graphics Device: Radeon RX 560 Series {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
[20:42:55] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach -> HiDef, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[20:42:57] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 800, Height: 480 -> 600, Fullscreen: False, Display: \\.\DISPLAY1
[20:42:59] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 800 -> 1920, Height: 600 -> 1017, Fullscreen: False, Display: \\.\DISPLAY1
[20:43:02] [8/DEBUG] [tML]: Assembly Resolve:  -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[20:43:02] [8/DEBUG] [tML]: Assembly Resolve:  -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[20:43:02] [8/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.10.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[20:43:03] [8/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Pdb, Version=0.10.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[20:43:03] [8/INFO] [Terraria]: JIT loading finished
[20:43:07] [7/INFO] [tML]: Finding Mods...
[20:43:07] [7/INFO] [tML]: Instantiating Mods...
[20:43:07] [7/INFO] [tML]: Initializing: ModLoader v0.11.5
[20:43:07] [7/INFO] [tML]: Setting up...
[20:43:07] [7/INFO] [tML]: Loading: ModLoader v0.11.5
[20:43:07] [7/INFO] [tML]: Adding Recipes...
[20:43:09] [8/DEBUG] [tML]: Web Request: http://javid.ddns.net/tModLoader/listmods.php
[20:43:30] [12/WARN] [tML]: Silently Caught Exception: 
System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 136.36.199.67:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   at System.Net.ServicePoint.ConnectSocketCallback(IAsyncResult asyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

[20:43:30] [12/WARN] [tML]: Silently Caught Exception: 
System.Net.WebException: Unable to connect to the remote server
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at System.Net.WebClient.UploadBitsRequestCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.HttpWebRequest.SetResponse(Exception E)
   at System.Net.HttpWebRequest.SetAndOrProcessResponse(Object responseOrException)
   at System.Net.ConnectionReturnResult.SetResponses(ConnectionReturnResult returnResult)
   at System.Net.Connection.CompleteConnectionWrapper(Object request, Object state)
   at System.Net.PooledStream.ConnectionCallback(Object owningObject, Exception e, Socket socket, IPAddress address)
   at System.Net.ServicePoint.ConnectSocketCallback(IAsyncResult asyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

[20:44:28] [1/WARN] [tML]: Silently Caught Exception: 
Microsoft.Xna.Framework.Graphics.DeviceLostException: Exception of type 'Microsoft.Xna.Framework.Graphics.DeviceLostException' was thrown.
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present(tagRECT* pSource, tagRECT* pDest, HWND__* hOverride)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.EndDraw()
   at Microsoft.Xna.Framework.Game.EndDraw()
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

[20:44:30] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1017, Fullscreen: False, Display: \\.\DISPLAY1
[20:44:40] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "http://javid.ddns.net/tModLoader/DirectModDownloadListing.php" 
[20:48:30] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "http://javid.ddns.net/tModLoader/DirectModDownloadListing.php" 
[20:51:27] [3/DEBUG] [tML]: Web Request: http://javid.ddns.net/tModLoader/listmods.php
[20:51:36] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "C:\Users\Collin\Documents\My Games\Terraria\ModLoader\Mods" 
[20:52:01] [11/DEBUG] [tML]: Web Request: http://javid.ddns.net/tModLoader/listmods.php

**Comment by Plantterror** [comment]
The mod browser is temporarily down. It will likely not be up until after a few days.

**Comment by Jofairden** [comment]
It says it's down because it _is_ down.
