### ISSUE TITLE
Error in Mod Browser Section

### ISSUE THREAD

**Issue by JustHmm** [tModLoader/tModLoader#709]
After updating tmodloader to latest version from 4-5 previous version, i started to get this error everytime when i open the mod browsing menu.  
I deleted terraria via steam and its save folder in documents folder, than re-installed it but still im getting this error:
screenshot of the error box: https://prnt.sc/pu6881
Any idea whats wrong? If i select continue, it keeps spamming that error every 2 seconds.
Is previous versions downloadable?

```
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.IconDownloadComplete(Object sender, DownloadDataCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadDataCompleted(DownloadDataCompletedEventArgs e)
   at System.Net.WebClient.DownloadDataOperationCompleted(Object arg)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Terraria
    Assembly Version: 1.3.5.1
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
ReLogic
    Assembly Version: 1.0.0.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
log4net
    Assembly Version: 2.0.8.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3081.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MonoMod.RuntimeDetour
    Assembly Version: 19.10.5.2
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
MonoMod.Utils
    Assembly Version: 19.10.5.2
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Mono.Cecil
    Assembly Version: 0.10.4.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
MonoMod.Utils.GetManagedSizeHelper
    Assembly Version: 0.0.0.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Ionic.Zip.Reduced
    Assembly Version: 1.9.1.8
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Microsoft.Xna.Framework.Game
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30901.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/Microsoft.Xna.Framework.Game/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.Game.dll
----------------------------------------
Microsoft.Xna.Framework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30901.0 built by: xnabldr
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/Microsoft.Xna.Framework/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.dll
----------------------------------------
Microsoft.Xna.Framework.Graphics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30901.0 built by: xnabldr
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/Microsoft.Xna.Framework.Graphics/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.Graphics.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3081.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3081.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.Xna.Framework.Xact
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30901.0 built by: xnabldr
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/Microsoft.Xna.Framework.Xact/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.Xact.dll
----------------------------------------
Microsoft.Xna.Framework.Input.Touch
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30901.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Xna.Framework.Input.Touch/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.Input.Touch.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Steamworks.NET
    Assembly Version: 9.1.0.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Microsoft.Xna.Framework.GamerServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30901.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Xna.Framework.GamerServices/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.GamerServices.dll
----------------------------------------
MP3Sharp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
NVorbis
    Assembly Version: 0.8.4.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Mono.Cecil.Mdb
    Assembly Version: 0.10.4.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Mono.Cecil.Pdb
    Assembly Version: 0.10.4.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///F:/-z-GAMES/_ValveApp/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


`
```

**Comment by JustHmm** [comment]
Just found the reason in another thread, imgur banned in my country. 
```
config.json 
"AvoidImgur": true,
```
