### ISSUE TITLE
Terraria crashes when I click anywhere related to mods/worlds

### ISSUE THREAD

**Issue by Serethan** [tModLoader/tModLoader#740]
### Description
I start up terraria with TModLoader updated and activated, I can´t open "mod browser" without having the game crashing. Then I try to open "mods" to unistall all mods I have active, to see which one is causing the issue, but my mouse would freeze, forcing me to close the game. Every time I try to create a new world with a new caracter It crashes aswell (It loads me into the spawn right before It does). I have the lastest version of TMD, (v0.11.5 currently) I´ve tried to install the previous one, which was the one I had no problems with but game will still crash.

### Log File
[02:03:36] [1/ERROR] [Terraria]: System.TypeLoadException: Could not load type 'Terraria.ModLoader.IO.TmodFile' from assembly 'Terraria, Version=1.3.5.1, Culture=neutral, PublicKeyToken=null'.
   at HamstarHelpers.Internals.Menus.ModUpdates.ModUpdatesMenuContext.DisplayModListVersions(UIState ui, IDictionary`2 modInfo)
   at HamstarHelpers.Internals.Menus.ModUpdates.ModUpdatesMenuContext.<>c__DisplayClass3_0.<Show>b__1(ModInfoListPromiseArguments args)
   at HamstarHelpers.Services.Promises.Promises.AddValidatedPromise[T](PromiseValidator validator, Func`2 func)
   at HamstarHelpers.Internals.Menus.ModUpdates.ModUpdatesMenuContext.<>c__DisplayClass3_0.<Show>b__0()
   at HamstarHelpers.Services.Timers.Timers.Update()
   at HamstarHelpers.Services.Timers.Timers._Update()
   at System.Action.Invoke()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)

### Reproduction frequency
It happens 100% of the time.

### Additional Information
Logs say im missing a file, so this is probably my fault and or an easy issue to solve. I don´t know programing at all, so sorry if It is.

**Comment by JavidPack** [comment]
You'll need to delete HamstarHelpers.tmod from the Mods directory and then start tmodloader

**Comment by Serethan** [comment]
Thanks you so much.
