### ISSUE TITLE
Tried to Install, and I get a weird error.

### ISSUE THREAD

**Issue by Kerenas** [tModLoader/tModLoader#754]
### Description
Im on Windows 64, recently repaired laptop. I was playing Terraria, and decided to download TModloader to play Calamity. So I tried to install this, both manually, and with the automatic installer, and I get the following error message, which I dont seem to get if I revert to Vanilla Terraria, then upgrade to v1.5. I also get the error upgrading from 1.5.

"System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
    at Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(AppId_tunOwnAppID)
   at Terraria.Social.Steam.CoreSocialModule.Initialize()
   at Terraria.SocialAPI.Initialize(Nullable`1 mode)
   at Terraria.Program.LaunchGame_0   "

If It helps, Terraria is on a separate drive from steam.

### Log File
[02:09:07] [1/INFO] [tML]: Starting tModLoader v0.11.6.1 Windows client (12/29/2019)
[02:09:07] [1/INFO] [tML]: Running on NetFramework 4.6.2
[02:09:07] [1/INFO] [tML]: Executable: D:\SteamLibrary\steamapps\common\Terraria\Terraria.exe
[02:09:07] [1/INFO] [tML]: Working Directory: D:\SteamLibrary\steamapps\common\Terraria
[02:09:07] [1/INFO] [tML]: Launch Parameters: 
[02:09:08] [1/WARN] [tML]: Silently Caught Exception: 
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(AppId_t unOwnAppID)
   at Terraria.Social.Steam.CoreSocialModule.Initialize()
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

[02:09:08] [1/FATAL] [Terraria]: Main engine crash
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(AppId_t unOwnAppID)
   at Terraria.Social.Steam.CoreSocialModule.Initialize()
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode)
   at Terraria.Program.LaunchGame_()

### Steps to Reproduce
Install newest TML from Vanilla, or upgrade from 1.5

### Expected behavior 
Terraria should start normally

### Actual behavior
Crash

### Reproduction frequency
Consistent. I will try with a completely new install of Vanilla, play for a bit, and see if that changes anything.

### Additional Information
Newly repaired computer, Windows install is ~1week old.

**Comment by Kerenas** [comment]
Edit: It seems that just moving to the main drive of steam worked. As deleting half the directory and verifying integrity. However, I did reproduce the issue very easily by upgrading to 1.5, then upgrading to 1.6.1

**Comment by brthh56uey7u56746i78u6i786ui7** [comment]
i have the same issue but i cant fix mine

**Comment by Kerenas** [comment]
change your install location of Terraria to the same drive as steam, then verify. RUn, boot into a world, play for 15 miniutes, exit, install tmodloader, run.

**Comment by GoodPro712** [comment]
Close
