### ISSUE TITLE
Mod fails to compile for unresolved FNA during pdb generation

### ISSUE THREAD

**Issue by sgkoishi** [tModLoader/tModLoader#785]
### Description
When I compile the mod in CI with `includePDB = true`, the game was unable to locate the FNA during writing PDB symbol. 
The source code of the mod does not locate in the Mod Source folder.
Similar to #672 

### Log File
```
Compiling XXX.XNA.dll
Compilation finished with 0 errors and 3 warnings
Compiling XXX.FNA.dll
Compilation finished with 0 errors and 3 warnings
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'FNA, Version=17.3.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)       at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Terraria.ModLoader.Core.ModCompile.BuildModForPlatform(BuildingMod mod, List`1& refMods, Boolean xna)
   at Terraria.ModLoader.Core.ModCompile.Build(BuildingMod mod)
   at Terraria.ModLoader.Core.ModCompile.BuildModCommandLine(String modFolder)
```

### Expected behavior 
Compile should not fail.

### Actual behavior
FNA was not found in all given search path, so `AssemblyResolutionException` was thrown.

### Additional Information
https://github.com/tModLoader/tModLoader/blob/8db1ce22ea6918ebbcfb96a4dabf3c365d998072/patches/tModLoader/Terraria.ModLoader.Core/ModCompile.cs#L491-L509
Only the `compile_temp` and game executable path was added, `ModCompile` was not.

**Comment by JavidPack** [comment]
By CI do you mean continuous integration? if so, you'll need to show how you are setting that up, since it seems to me to be an issue with that.

**Comment by sgkoishi** [comment]
> 
> 
> By CI do you mean continuous integration? if so, you'll need to show how you are setting that up, since it seems to me to be an issue with that.

Pretty much it's just a simple call `Process.Start(Path.Combine(GAME_PATH, "tModLoaderServer.exe"), "-build XXX -unsafe")` - I've reproduce it locally using cmd.
Attaching with dnSpy locate the problem to the `asm.Write` - the game can not find FNA.dll in either game folder or `compile_temp` folder (it's in `ModCompile` folder). 
https://github.com/tModLoader/tModLoader/blob/8db1ce22ea6918ebbcfb96a4dabf3c365d998072/patches/tModLoader/Terraria.ModLoader.Core/ModCompile.cs#L506-L509

This problem doesn't appear after I set `includePDB = false` (as line 498)
https://github.com/tModLoader/tModLoader/blob/8db1ce22ea6918ebbcfb96a4dabf3c365d998072/patches/tModLoader/Terraria.ModLoader.Core/ModCompile.cs#L498-L499

**Comment by Chicken-Bones** [comment]
Send me a test mod. I'll fix it

**Comment by sgkoishi** [comment]
[tML_issue785.zip](https://github.com/tModLoader/tModLoader/files/4151280/tML_issue785.zip)
Here's the minimal version.

build.txt:
```
displayName = tML_issue785
author = SGKoishi
version = 1.0
includePDB = true
```
code:
```
using Terraria.ModLoader;
using Microsoft.Xna.Framework.Graphics;

namespace tML_issue785
{
    public class tML_issue785 : Mod
    {
        private void method(SpriteEffects sf = SpriteEffects.None)
        {
            
        }
    }
}
```
