### ISSUE TITLE
Tmodloader won’t work at all anymore

### ISSUE THREAD

**Issue by rodneyman69** [tModLoader/tModLoader#816]
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
at Terraria.ModLoader.Logging.Init()
at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

I had the 64 bit version, and one day it just stopped working out of the blue. No updates or anything. Went as far as resetting PC since this is the only game I play on it. Windows 10 version 1909

**Comment by rodneyman69** [comment]
Edit - Meant to include that normal tmod and 64 bit version give this error but regular terraria works fine

**Comment by Chicken-Bones** [comment]
Full client.log file please.

**Comment by rodneyman69** [comment]
> Full client.log file please.

3/21/2020 8:42:23 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/21/2020 8:48:44 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/21/2020 11:17:52 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/21/2020 11:22:05 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/21/2020 11:34:23 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 2:40:49 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 2:55:44 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 2:57:31 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 3:05:16 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 3:06:01 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 3:06:07 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 3:06:23 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 3:07:06 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 3:07:16 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 3:08:37 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 3:09:57 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 3:18:59 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

3/22/2020 3:19:27 PM
System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.mprotect(IntPtr start, IntPtr len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.Init()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

**Comment by Chicken-Bones** [comment]
Nono, I mean attach the client.log file, not just the same error 20 times

**Comment by rodneyman69** [comment]
oh sorry bout that
[client.log](https://github.com/tModLoader/tModLoader/files/4367102/client.log)

**Comment by JavidPack** [comment]
This looks like a bug we noticed a while ago when a Windows user has a folder named C:/Applications or C:/System on their computer. These folder names confuse some code we depend on. The solution would be to rename those folders if this is the case, at least until next tmodloader.

If that is not the case, I'd suggest a full wipe of the install folder, then have steam install it again.

**Comment by rodneyman69** [comment]
Ty so much bro that fixed it. Renamed it to something stupid and now it works perfectly

**Comment by 0x0ade** [comment]
Occasional reminder that there's been a proper fix for this issue in MonoMod for quite a while now 😅 https://github.com/MonoMod/MonoMod.Common/issues/2

**Comment by nRs7** [comment]
DUDE THANK YOU SO MUCH I CREATED AN ACCOUNT JUST TO THANK YOU GUYS !! I have had this problem for so long and I didn't know renaming files was the easy fix thank you I appreciate that some people actually help out other people that are struggling :)
