### ISSUE TITLE
Bad CRC32 in GZIP

### ISSUE THREAD

**Issue by darkdex52** [tModLoader/tModLoader#842]
### Description
When Starting fresh install of Terraria and fresh install of tModLoader and trying to access Mod Browser, it outputs this error and quite back to menu, not showing any mods

```
[20:57:38] [7/ERROR] [tML]: The mod browser encountered an error.

Bad CRC32 in GZIP trailer. (actual(D228D1FF)!=expected(C4CC25CD))
   at Ionic.Zlib.ZlibBaseStream.finish()
   at Ionic.Zlib.ZlibBaseStream.Close()
   at Ionic.Zlib.GZipStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamReader.Dispose(Boolean disposing)
   at System.IO.TextReader.Dispose()
   at Terraria.ModLoader.UI.ModBrowser.UIModBrowser.PopulateFromJson(LocalMod[] installedMods, String json)
[20:57:41] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "C:\Users\darkd\Documents\My Games\Terraria\ModLoader\Logs\client.log"
```

### Log file
https://pastebin.com/raw/BeCrWuNp

### Steps to reproduce

1. Install Terraria and tModLoader
2. Open Terraria and mod browser
3. Error

### Expected behavior 
Showing available mods to download

### Actual behavior
Not that

### Reproduction frequency
100% of the time

### Additional Information
Windows 10 x64 1909

**Comment by Mirsario** [comment]
Mod Browser has had a plenty of issues in the last few weeks. Does this still happen for you?

**Comment by Chicken-Bones** [comment]
Closing due to inactivity, feel free to re-open if it occurs again
