### ISSUE TITLE
`Failed to resolve assembly for Terraria v1.3.5.3 etc.` during compile (in-game and VS)

### ISSUE THREAD

**Issue by hamstar0** [tModLoader/tModLoader#896]
### Description
Mod compile fails in VS and in-game with the given error message ([Mod Helpers v5.7.0.1](https://github.com/hamstar0/tml-hamstarhelpers-mod), tML 0.11.7). Not much helpful information seems available.

### Log file
```[16:34:53] [10/INFO] [tML]: Reading properties: HamstarHelpers
[16:34:53] [10/INFO] [tML]: Building: HamstarHelpers
[16:34:53] [10/INFO] [tML]: Compiling HamstarHelpers.XNA.dll
[16:34:53] [10/DEBUG] [tML]: Assembly Resolve: RoslynWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[16:34:53] [10/DEBUG] [tML]: Assembly Resolve: RoslynWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
[16:34:53] [10/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[16:34:53] [10/DEBUG] [tML]: Assembly Resolve: RoslynWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
[16:34:53] [10/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
[16:34:53] [10/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[16:34:53] [10/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[16:34:53] [10/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[16:34:53] [10/DEBUG] [tML]: Assembly Resolve: System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a -> System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[16:34:58] [10/DEBUG] [tML]: Assembly Resolve:  -> Microsoft.CodeAnalysis.CSharp.resources, Version=2.10.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
[16:34:58] [10/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> Microsoft.CodeAnalysis.CSharp.resources, Version=2.10.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
[16:34:58] [10/DEBUG] [tML]: Assembly Resolve:  -> Microsoft.CodeAnalysis.CSharp.resources, Version=2.10.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
[16:34:58] [10/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> Microsoft.CodeAnalysis.CSharp.resources, Version=2.10.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
[16:34:58] [10/INFO] [tML]: Compilation finished with 0 errors and 6 warnings
[16:34:58] [10/WARN] [tML]: C:\Users\Spinach\Documents\My Games\Terraria\ModLoader\Mod Sources\HamstarHelpers\Helpers\Players\PlayerNPCHelpers.cs(46,30) : warning CS0618: 'Lang.dialog(int, bool)' is obsolete: 'dialog is deprecated. Please use Language.GetText instead.'
[16:34:58] [10/WARN] [tML]: C:\Users\Spinach\Documents\My Games\Terraria\ModLoader\Mod Sources\HamstarHelpers\Helpers\Players\PlayerNPCHelpers.cs(47,25) : warning CS0618: 'Lang.dialog(int, bool)' is obsolete: 'dialog is deprecated. Please use Language.GetText instead.'
[16:34:58] [10/WARN] [tML]: C:\Users\Spinach\Documents\My Games\Terraria\ModLoader\Mod Sources\HamstarHelpers\Helpers\Players\PlayerNPCHelpers.cs(48,25) : warning CS0618: 'Lang.dialog(int, bool)' is obsolete: 'dialog is deprecated. Please use Language.GetText instead.'
[16:34:58] [10/WARN] [tML]: C:\Users\Spinach\Documents\My Games\Terraria\ModLoader\Mod Sources\HamstarHelpers\Helpers\Players\PlayerNPCHelpers.cs(49,25) : warning CS0618: 'Lang.dialog(int, bool)' is obsolete: 'dialog is deprecated. Please use Language.GetText instead.'
[16:34:58] [10/WARN] [tML]: C:\Users\Spinach\Documents\My Games\Terraria\ModLoader\Mod Sources\HamstarHelpers\Helpers\NPCs\NPCTownHelpers.cs(67,90) : warning CS0618: 'Lang.misc' is obsolete: 'Lang arrays have been replaced with the new Language.GetText system.'
[16:34:58] [10/WARN] [tML]: C:\Users\Spinach\Documents\My Games\Terraria\ModLoader\Mod Sources\HamstarHelpers\Helpers\Recipes\RecipeGroupHelpers.cs(71,12) : warning CS0618: 'Lang.misc' is obsolete: 'Lang arrays have been replaced with the new Language.GetText system.'
[16:34:58] [10/ERROR] [tML]: Failed to resolve assembly: 'Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null'
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Terraria.ModLoader.Core.ModCompile.BuildModForPlatform(BuildingMod mod, List`1& refMods, Boolean xna) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 506
   at Terraria.ModLoader.Core.ModCompile.Build(BuildingMod mod) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 360
   at Terraria.ModLoader.Core.ModCompile.Build(String modFolder) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 320
   at Terraria.ModLoader.UI.UIBuildMod.<>c__DisplayClass5_0.<Build>b__0(ModCompile mc) in tModLoader\Terraria.ModLoader.UI\UIBuildMod.cs:line 31
   at Terraria.ModLoader.UI.UIBuildMod.BuildMod(Action`1 buildAction, Boolean reload) in tModLoader\Terraria.ModLoader.UI\UIBuildMod.cs:line 67
```

### Steps to reproduce
See title.

### Expected behavior 
Works.

### Actual behavior
Don't works.

### Reproduction frequency
Always.

### Additional Information
I've had this issue before. A while ago, I solved this by removing a SpriteEffect parameter from one of my API methods. Recently (tML 11.7), my Destructible Tiles mod had this issue, and I solved it with this fix: https://github.com/hamstar0/tml-destructibletiles-mod/commit/8ae14f8beec0a2dc94b941df42aa52477379d577

**Comment by PoroCYon** [comment]
This can probably be fixed by hooking into `AppDomain.CurrentDomain.AssemblyResolve` and returning the correct `Assembly` when something called "Terraria" is being looked for. [Prism did this](https://github.com/TerrariaPrismTeam/Prism/blob/develop/Prism/AssemblyResolver.cs#L102), ok if I make a similar PR?

**Comment by hamstar0** [comment]
**Update:** It appears the issue is caused by method parameters using enums (with default values?) from other assemblies.
