### ISSUE TITLE
World Gen bug

### ISSUE THREAD

**Issue by ghost** [tModLoader/tModLoader#912]
### Description
World gen has been altered after tmodloader becomes a Steam DLC separated with the main terraria 1.4

### Before 1.3.5 with Tmod
![Annotation 2020-05-19 093554](https://user-images.githubusercontent.com/56964256/82269719-d92da900-99b5-11ea-9bf3-b4601f086582.png)

### Tmod from Steam DLC
![Annotation 2020-05-19 094119](https://user-images.githubusercontent.com/56964256/82269764-f6627780-99b5-11ea-9495-144637b24e1b.png)

### Steps to reproduce

1. Create a World in Tmodloader Steam DLC
2. Large, Expert and any evil
3. WorldGen Previewer will show that the sulphuric sea from Calamity always generate higher than the beach

### Expected behavior 
The Sulphuric sea should generate at the same level as the beach showed in 1.3.5 Tmodloader

### Actual behavior
After tmodloader becomes a DLC for steam, the sulphuric sea always generate higher than the beach

### Reproduction frequency
10 out of 10 tries with large, expert and any evil, no other mod except calamity and world gen previewer.

### Additional Information
Tmodloader from steam DLC is the one that I used. World before 1.4 can be viewed using terra map
now it shows. Generating a World with the a 1.3.5.3 seed will result in normal generation.
![Annotation 2020-05-19 095508](https://user-images.githubusercontent.com/56964256/82270075-f0b96180-99b6-11ea-8db6-04115888c648.png)
and gives 
`System.Exception: World file tiles list start is not where it's expected to be. Expected: 2805 Actual: 1130
   at TerraMap.Data.World.ReadWorldVersion2(BinaryReader reader) in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 459
   at TerraMap.Data.World.Read(String filename) in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 431
   at TerraMap.Data.World.<>c__DisplayClass374_0.<ReadAsync>b__0() in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 393
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<Open>d__24.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 287
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<Open>d__23.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 254
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<OnOpenWorldFile>d__56.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 1189
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by Mirsario** [comment]
The sulphuric sea has always been bugged, and I saw it getting generated in the skies months prior to the steam release being announced.

**Comment by Jofairden** [comment]
I highly doubt this is related to TML since its just a mod generation being broken

**Comment by JavidPack** [comment]
Someone could test this with worldgenpreviewer and the same seed on 0.11.6.2 and 0.11.7+. If there is a glaring difference, we might have made a mistake. We'll get to this eventually, but if someone wants to be proactive, they can do it for us.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
