### ISSUE TITLE
NPC.modNPC is sometimes null for modded NPCs after SetDefaults has been called

### ISSUE THREAD

**Issue by PoroCYon** [tModLoader/tModLoader#932]
### Description

`NPC.modNPC` seems to be null sometimes, even for modded NPCs (i.e. `NPCLoader.IsModNPC` returns true), causing NullReferenceExceptions in eg. `NPCLoader.DrawHealthBar`.

### Log file

This is the standard way of how things would happen:

```
[10:35:51] [1/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.NPCLoader.DrawHealthBar(NPC npc, Single& scale)
   at Terraria.Main.DrawInterface_14_EntityHealthBars()
   at Terraria.Main.<SetupDrawInterfaceLayers>b__1637_10()
   at Terraria.UI.LegacyGameInterfaceLayer.DrawSelf()
   at Terraria.UI.GameInterfaceLayer.Draw()
   at Terraria.Main.DrawInterface(GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

[10:35:51] [1/WARN] [tML]: Silently Caught Exception: 
System.InvalidOperationException: Begin cannot be called again until End has been successfully called.
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformMatrix)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

[10:35:51] [1/ERROR] [Terraria]: System.InvalidOperationException: Begin cannot be called again until End has been successfully called.
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformMatrix)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
[10:35:51] [1/FATAL] [Terraria]: Main engine crash
System.InvalidOperationException: Begin cannot be called again until End has been successfully called.
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformMatrix)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
```

After inserting some hooks for logging more stuff, suppressing `Main.ignoreErrors`, etc., I got the following log, with source code lines etc.:

```
[21:51:04] [1/WARN] [tML]: W: NPC name:Black Recluse, active:True, whoAmI:19 type=580 modNPC is null!
[21:51:04] [1/WARN] [tML]:   at pcytest.pcytest.Hook_IsModNPC (On.Terraria.ModLoader.NPCLoader+orig_IsModNPC orig, Terraria.NPC npc) [0x00000] in <4551e996f7084860821c53137e690db3>:0 
  at MonoMod.Utils.DynamicMethodDefinition.DMD<DMD<Hook<Terraria.ModLoader.NPCLoader::IsModNPC>?874177463>?1248114620::Hook<Terraria.ModLoader.NPCLoader::IsModNPC>?874177463> (Terraria.NPC ) [0x00000] in <ee8de927ab844aca96d747879e280cc6>:0 
  at Terraria.ModLoader.NPCLoader.DrawHealthBar (Terraria.NPC npc, System.Single& scale) [0x000d4] in <4af976ae0b5b427fab8847c2a8f3792a>:0 
  at Terraria.Main.DrawInterface_14_EntityHealthBars () [0x001db] in <4af976ae0b5b427fab8847c2a8f3792a>:0 
  at Terraria.Main.<SetupDrawInterfaceLayers>b__1637_10 () [0x00000] in <4af976ae0b5b427fab8847c2a8f3792a>:0 
  at Terraria.UI.LegacyGameInterfaceLayer.DrawSelf () [0x00000] in <4af976ae0b5b427fab8847c2a8f3792a>:0 
  at Terraria.UI.GameInterfaceLayer.Draw () [0x00056] in <4af976ae0b5b427fab8847c2a8f3792a>:0 
  at Terraria.Main.DrawInterface (Microsoft.Xna.Framework.GameTime gameTime) [0x00030] in <4af976ae0b5b427fab8847c2a8f3792a>:0 
  at Terraria.Main.DoDraw (Microsoft.Xna.Framework.GameTime gameTime) [0x04f92] in <4af976ae0b5b427fab8847c2a8f3792a>:0 
  at Terraria.Main.DMD<Terraria.Main::Draw> (Terraria.Main , Microsoft.Xna.Framework.GameTime ) [0x00000] in <4af976ae0b5b427fab8847c2a8f3792a>:0 
  at MonoMod.Utils.DynamicMethodDefinition.DMD<DMD<Trampoline<Terraria.Main::Draw>?-1045819394>?-333984535::Trampoline<Terraria.Main::Draw>?-1045819394> (Terraria.Main , Microsoft.Xna.Framework.GameTime ) [0x00000] in <ee8de927ab844aca96d747879e280cc6>:0 
  at pcytest.pcytest.CheckSB_Main_Draw (On.Terraria.Main+orig_Draw orig, Terraria.Main self, Microsoft.Xna.Framework.GameTime gt) [0x00000] in <4551e996f7084860821c53137e690db3>:0 
  at MonoMod.Utils.DynamicMethodDefinition.DMD<DMD<Hook<Terraria.Main::Draw>?855820461>?-558700442::Hook<Terraria.Main::Draw>?855820461> (Terraria.Main , Microsoft.Xna.Framework.GameTime ) [0x00000] in <ee8de927ab844aca96d747879e280cc6>:0 
  at Microsoft.Xna.Framework.Game.Tick () [0x00000] in <bc6b38abaaf04135afbd0534ec7f6b92>:0 
  at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop (Microsoft.Xna.Framework.Game game) [0x00000] in <bc6b38abaaf04135afbd0534ec7f6b92>:0 
  at Microsoft.Xna.Framework.Game.Run () [0x00000] in <bc6b38abaaf04135afbd0534ec7f6b92>:0 
  at Terraria.Program.LaunchGame_ () [0x00082] in <4af976ae0b5b427fab8847c2a8f3792a>:0 
  at Terraria.Program.LaunchGame (System.String[] args, System.Boolean monoArgs) [0x000ac] in <4af976ae0b5b427fab8847c2a8f3792a>:0 
  at MonoLaunch.Main (System.String[] args) [0x00038] in <4af976ae0b5b427fab8847c2a8f3792a>:0 
[21:51:04] [1/ERROR] [Terraria]: System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.ModLoader.NPCLoader.DrawHealthBar (NPC npc, Single& scale) in tModLoader\Terraria.ModLoader\NPCLoader.cs:751 
  at Terraria.Main.DrawInterface_14_EntityHealthBars () in tModLoader\Terraria\Main.cs:34088 
  at Terraria.Main.<SetupDrawInterfaceLayers>b__1637_10 () in tModLoader\Terraria\Main.cs:33176 
  at Terraria.UI.LegacyGameInterfaceLayer.DrawSelf () in tModLoader\Terraria.UI\LegacyGameInterfaceLayer.cs:12 
  at Terraria.UI.GameInterfaceLayer.Draw () in tModLoader\Terraria.UI\GameInterfaceLayer.cs:38 
  at Terraria.Main.DrawInterface (GameTime gameTime) in tModLoader\Terraria\Main.cs:33300 
  at Terraria.Main.DoDraw (GameTime gameTime) in tModLoader\Terraria\Main.cs:48510 
  at (wrapper dynamic-method) Terraria.Main.DMD<Terraria.Main::Draw>(Main,GameTime)
[21:51:04] [1/FATAL] [Terraria]: Main engine crash
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object) ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.ModLoader.NPCLoader.DrawHealthBar (NPC npc, Single& scale) in tModLoader\Terraria.ModLoader\NPCLoader.cs:751 
  at Terraria.Main.DrawInterface_14_EntityHealthBars () in tModLoader\Terraria\Main.cs:34088 
  at Terraria.Main.<SetupDrawInterfaceLayers>b__1637_10 () in tModLoader\Terraria\Main.cs:33176 
  at Terraria.UI.LegacyGameInterfaceLayer.DrawSelf () in tModLoader\Terraria.UI\LegacyGameInterfaceLayer.cs:12 
  at Terraria.UI.GameInterfaceLayer.Draw () in tModLoader\Terraria.UI\GameInterfaceLayer.cs:38 
  at Terraria.Main.DrawInterface (GameTime gameTime) in tModLoader\Terraria\Main.cs:33300 
  at Terraria.Main.DoDraw (GameTime gameTime) in tModLoader\Terraria\Main.cs:48510 
  at (wrapper dynamic-method) Terraria.Main.DMD<Terraria.Main::Draw>(Main,GameTime)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.DMD<DMD<Trampoline<Terraria.Main::Draw>?-1045819394>?-333984535::Trampoline<Terraria.Main::Draw>?-1045819394>(Main,GameTime)
  at pcytest.pcytest.CheckSB_Main_Draw (orig_Draw orig, Main self, GameTime gt) [0x0000d] in data-0x7f40dc57eff0 
   --- End of inner exception stack trace ---
  at pcytest.pcytest.CheckSB_Main_Draw (orig_Draw orig, Main self, GameTime gt) [0x00059] in data-0x7f40dc57eff0 
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.DMD<DMD<Hook<Terraria.Main::Draw>?855820461>?-558700442::Hook<Terraria.Main::Draw>?855820461>(Main,GameTime)
  at Microsoft.Xna.Framework.Game.Tick () [0x001fc] in FNA.dll 
  at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop (Game game) [0x005b6] in FNA.dll 
  at Microsoft.Xna.Framework.Game.Run () [0x0002c] in FNA.dll 
  at Terraria.Program.LaunchGame_ () in tModLoader\Terraria\Program.cs:250 
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.ModLoader.NPCLoader.DrawHealthBar (NPC npc, Single& scale) in tModLoader\Terraria.ModLoader\NPCLoader.cs:751 
  at Terraria.Main.DrawInterface_14_EntityHealthBars () in tModLoader\Terraria\Main.cs:34088 
  at Terraria.Main.<SetupDrawInterfaceLayers>b__1637_10 () in tModLoader\Terraria\Main.cs:33176 
  at Terraria.UI.LegacyGameInterfaceLayer.DrawSelf () in tModLoader\Terraria.UI\LegacyGameInterfaceLayer.cs:12 
  at Terraria.UI.GameInterfaceLayer.Draw () in tModLoader\Terraria.UI\GameInterfaceLayer.cs:38 
  at Terraria.Main.DrawInterface (GameTime gameTime) in tModLoader\Terraria\Main.cs:33300 
  at Terraria.Main.DoDraw (GameTime gameTime) in tModLoader\Terraria\Main.cs:48510 
  at (wrapper dynamic-method) Terraria.Main.DMD<Terraria.Main::Draw>(Main,GameTime)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.DMD<DMD<Trampoline<Terraria.Main::Draw>?-1045819394>?-333984535::Trampoline<Terraria.Main::Draw>?-1045819394>(Main,GameTime)
  at pcytest.pcytest.CheckSB_Main_Draw (orig_Draw orig, Main self, GameTime gt) [0x0000d] in data-0x7f40dc57eff0 <---
```

So it's [this code](https://github.com/tModLoader/tModLoader/blob/master/patches/tModLoader/Terraria.ModLoader/NPCLoader.cs#L751) that's erroring.

### Steps to reproduce

The following code is used:

```cs
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace pcytest.NPCs
{
	// Party Zombie (ExampleMod) copypasta
	public class DesertCrawler : ModNPC
	{
		public override void SetStaticDefaults()
		{
			DisplayName.SetDefault("Desert Crawler");
			Main.npcFrameCount[npc.type] = Main.npcFrameCount[NPCID.BlackRecluse];
		}

		public override void SetDefaults()
		{
			Main.NewText("setdef hi");
			npc.width = 40;
			npc.height = 22;
			npc.damage = 22;
			npc.defense = 9;
			npc.lifeMax = 245;
			npc.HitSound = SoundID.NPCHit2;
			npc.DeathSound = SoundID.NPCDeath12;
			npc.value = 100f;
			npc.knockBackResist = 0.6f;
			npc.aiStyle = 3;
			aiType = NPCID.BlackRecluse;
			animationType = NPCID.BlackRecluse;
			banner = Item.NPCtoBanner(NPCID.BlackRecluse);
			bannerItem = Item.BannerToItem(banner);
		}

		public override void NPCLoot()
		{
			Main.NewText("hi hi");
			if (Main.rand.Next(7) < 2) // a 2 in 7 chance
				Item.NewItem(npc.getRect(), ItemID.AntlionMandible, 1);
		}

		public override float SpawnChance(NPCSpawnInfo spawnInfo)
		{
			Main.NewText("sc hi");
			return SpawnCondition.DesertCave.Chance * 0.2f;
		}
	}
}
```

1. Use the code above
2. Try getting the NPC to spawn (seems to work normally (i.e. no crashes) with the CheatSheet mod, but the error sometimes occurs when trying to get it to spawn in the world?)
3. Wait for a crash. Might take a while, but it was always within 10 minutes in my tests?

### Expected behavior 
`NPC.modNPC` isn't null, so hooks can be called properly

### Actual behavior
`NPC.modNPC` is sometimes null, causing NullReferenceExceptions in eg. `NPCLoader.DrawHealthBar`. This exception is supporessed, but it causes the main SpriteBatch to enter an invalid state, causing more errors down the line, culminating in a fatal exception.

### Reproduction frequency
It's flaky, sadly.

### Additional Information

This is my code that hooks `IsModNPC` (part of the main mod class):

```cs
		static bool Hook_IsModNPC(On.Terraria.ModLoader.NPCLoader.orig_IsModNPC
				orig, NPC npc) {
			bool rv = orig(npc);
			if (npc.modNPC == null && rv) {
				Main.NewText("W: NPC " + npc + " type=" + npc.type + " modNPC is null!");
				Main.NewText(new StackTrace().ToString());
			}
			return rv;
		}

		public override void Load() {
			On.Terraria.ModLoader.NPCLoader.IsModNPC += Hook_IsModNPC;
		}
		public override void Unload() {
			On.Terraria.ModLoader.NPCLoader.IsModNPC -= Hook_IsModNPC;
		}
```

The code also causes these log messages to be shown when `SetDefaults` is  called (where it's expected), but also in `DrawHealthBar` (shown in the stack trace), where this shouldn't be the case.

I don't know if this only happens with NPCs, or only in `DrawHealthBar`, there's no reason I can see it's only confined to these conditions, but, ¯\\\_(ツ)\_/¯

EDIT: [full source code etc](https://gitlab.ulyssis.org/pcy/tmlhax). Yes it's supposed to summon devils.

**Comment by Jofairden** [comment]
That's really odd, no other mods enabled etc?
The check should work since it just checks the .type
Though that draw line should just use a null-conditional `npc.modNPC?.DrawHealthBar(Main.HealthBarDrawSettings, ref scale, ref position);`

**Comment by PoroCYon** [comment]
The only other mod was CheatSheet, but I don't think it would've made much of a difference.

That edit would work around the issue, but shouldn't it be fixed properly? Because I don't think it's supposed to be null to begin with.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
