### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by anberry87** [tModLoader/tModLoader#940]
### Log file
5/27/2020 2:01:17 PM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Texture2D'.
   at Microsoft.Xna.Framework.Helpers.CheckDisposed(Object obj, IntPtr pComPtr)
   at Microsoft.Xna.Framework.Graphics.TextureCollection.set_Item(Int32 index, Texture value)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.RenderBatch(Texture2D texture, SpriteInfo[] sprites, Int32 offset, Int32 count)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Flush()
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.End()
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.ModLoader.UI.UIModSources.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UserInterface.Draw(SpriteBatch spriteBatch, GameTime time)
   at Terraria.Main.DrawMenu(GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()

### Steps to reproduce
3 ways

Opening a mod sources or opening mod(list) or mod browser

### Expected behavior 
There were no crashes before i downloaded tmodloader in steam.
originaly, i used direct download.

### Actual behavior

Crash
### Reproduction frequency

Everytime

### Additional Information

Thats it

**Comment by GoodPro712** [comment]
Are you able to hold shift when loading and see if it still crashes

**Comment by anberry87** [comment]
> Are you able to hold shift when loading and see if it still crashes

Yes it stil crashes

**Comment by Chicken-Bones** [comment]
Can you attach the log file please?

**Comment by Solxanich** [comment]
Hello @anberry87,
I'm currently reviewing stale issues, and would like to confirm if you are still experiencing this issue in the latest version 0.11.8.1 of tModLoader.
If not, could you please close the issue?
If so, could you please provide the most recent information from its occurrence, per Chicken-Bones's request?
Thank you for your time.
