### ISSUE TITLE
MysteryTile.MouseOver throws exception in multiplayer

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#952]
### Description

In multiplayer, [infos[frame.FrameID]](https://github.com/tModLoader/tModLoader/blob/master/patches/tModLoader/Terraria.ModLoader.Default/MysteryTile.cs#L15) throwing ArgumentOutOfRangeException because `infos` data isn't sent to clients on join so the list stays empty.

### Log file
```
[11:57:12] [1/WARN] [tML]: Silently Caught Exception: 
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Terraria.ModLoader.Default.MysteryTile.MouseOver(Int32 i, Int32 j)
   at Terraria.ModLoader.TileLoader.MouseOver(Int32 i, Int32 j)
   at Terraria.Player.TileInteractionsMouseOver(Int32 myX, Int32 myY)
   at Terraria.Player.TileInteractionsCheck(Int32 myX, Int32 myY)
```

### Steps to reproduce
Start a server with unloaded tiles, and join it and then mouseover. Your player will stop drawing its vanity if it has any because the player loop breaks during MouseOver.

### Additional Information
The underlying cause is that the `infos` list isn't sent to clients. Concidering that this list has only been used for serverside tasks before, just sending it over to all clients for the sole purpose of mouseover text might be unnecessary. (Plus, if you would write this code in the proper hooks for a `ModWorld`, it would be sent each time `MessageID.WorldData` is sent, and it would be redundant after the initial join).
Some thoughts on how to make mouse over work for clients (or not):
1. Simple fix would be to send the list like you would send any list that belongs to a ModWorld. Then you would have to check if there are no repercussions clientside having this list filled with data.
2. Separate list that is sent ONLY ONCE (not for each `MessageID.WorldData`) that only contains the relevant mouseover data required, and is only used for that. Will be used in singleplayer too.
3. Not show the mouseover entirely clientside, then it would be a simple range check or `Main.netMode` check:
```cs
var infos = ModContent.GetInstance<MysteryTilesWorld>().infos;
int frameID = frame.FrameID;
if (frameID >= 0 && frameID < infos.Count) {
	var info = infos[frameID];

	if (info != null) {
```

**Comment by direwolf420** [comment]
PR that added this: #824
